// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerBookingRepository creates a new instance of MockCustomerBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerBookingRepository {
	mock := &MockCustomerBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerBookingRepository is an autogenerated mock type for the CustomerBookingRepository type
type MockCustomerBookingRepository struct {
	mock.Mock
}

type MockCustomerBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerBookingRepository) EXPECT() *MockCustomerBookingRepository_Expecter {
	return &MockCustomerBookingRepository_Expecter{mock: &_m.Mock}
}

// CancelBooking provides a mock function for the type MockCustomerBookingRepository
func (_mock *MockCustomerBookingRepository) CancelBooking(ctx context.Context, bookingID int) error {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerBookingRepository_CancelBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBooking'
type MockCustomerBookingRepository_CancelBooking_Call struct {
	*mock.Call
}

// CancelBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
func (_e *MockCustomerBookingRepository_Expecter) CancelBooking(ctx interface{}, bookingID interface{}) *MockCustomerBookingRepository_CancelBooking_Call {
	return &MockCustomerBookingRepository_CancelBooking_Call{Call: _e.mock.On("CancelBooking", ctx, bookingID)}
}

func (_c *MockCustomerBookingRepository_CancelBooking_Call) Run(run func(ctx context.Context, bookingID int)) *MockCustomerBookingRepository_CancelBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerBookingRepository_CancelBooking_Call) Return(err error) *MockCustomerBookingRepository_CancelBooking_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerBookingRepository_CancelBooking_Call) RunAndReturn(run func(ctx context.Context, bookingID int) error) *MockCustomerBookingRepository_CancelBooking_Call {
	_c.Call.Return(run)
	return _c
}

// CheckInBooking provides a mock function for the type MockCustomerBookingRepository
func (_mock *MockCustomerBookingRepository) CheckInBooking(ctx context.Context, bookingID int) error {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CheckInBooking")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerBookingRepository_CheckInBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckInBooking'
type MockCustomerBookingRepository_CheckInBooking_Call struct {
	*mock.Call
}

// CheckInBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
func (_e *MockCustomerBookingRepository_Expecter) CheckInBooking(ctx interface{}, bookingID interface{}) *MockCustomerBookingRepository_CheckInBooking_Call {
	return &MockCustomerBookingRepository_CheckInBooking_Call{Call: _e.mock.On("CheckInBooking", ctx, bookingID)}
}

func (_c *MockCustomerBookingRepository_CheckInBooking_Call) Run(run func(ctx context.Context, bookingID int)) *MockCustomerBookingRepository_CheckInBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerBookingRepository_CheckInBooking_Call) Return(err error) *MockCustomerBookingRepository_CheckInBooking_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerBookingRepository_CheckInBooking_Call) RunAndReturn(run func(ctx context.Context, bookingID int) error) *MockCustomerBookingRepository_CheckInBooking_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmBooking provides a mock function for the type MockCustomerBookingRepository
func (_mock *MockCustomerBookingRepository) ConfirmBooking(ctx context.Context, bookingID int) error {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmBooking")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerBookingRepository_ConfirmBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmBooking'
type MockCustomerBookingRepository_ConfirmBooking_Call struct {
	*mock.Call
}

// ConfirmBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
func (_e *MockCustomerBookingRepository_Expecter) ConfirmBooking(ctx interface{}, bookingID interface{}) *MockCustomerBookingRepository_ConfirmBooking_Call {
	return &MockCustomerBookingRepository_ConfirmBooking_Call{Call: _e.mock.On("ConfirmBooking", ctx, bookingID)}
}

func (_c *MockCustomerBookingRepository_ConfirmBooking_Call) Run(run func(ctx context.Context, bookingID int)) *MockCustomerBookingRepository_ConfirmBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerBookingRepository_ConfirmBooking_Call) Return(err error) *MockCustomerBookingRepository_ConfirmBooking_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerBookingRepository_ConfirmBooking_Call) RunAndReturn(run func(ctx context.Context, bookingID int) error) *MockCustomerBookingRepository_ConfirmBooking_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBookingWithSeatLock provides a mock function for the type MockCustomerBookingRepository
func (_mock *MockCustomerBookingRepository) CreateBookingWithSeatLock(ctx context.Context, onlineCustomerID int64, showID int, seatStatusIDs []int, totalPrice float64, expiresAt time.Time, bookingRef string) (*model.Booking, error) {
	ret := _mock.Called(ctx, onlineCustomerID, showID, seatStatusIDs, totalPrice, expiresAt, bookingRef)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookingWithSeatLock")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, []int, float64, time.Time, string) (*model.Booking, error)); ok {
		return returnFunc(ctx, onlineCustomerID, showID, seatStatusIDs, totalPrice, expiresAt, bookingRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, []int, float64, time.Time, string) *model.Booking); ok {
		r0 = returnFunc(ctx, onlineCustomerID, showID, seatStatusIDs, totalPrice, expiresAt, bookingRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, []int, float64, time.Time, string) error); ok {
		r1 = returnFunc(ctx, onlineCustomerID, showID, seatStatusIDs, totalPrice, expiresAt, bookingRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerBookingRepository_CreateBookingWithSeatLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBookingWithSeatLock'
type MockCustomerBookingRepository_CreateBookingWithSeatLock_Call struct {
	*mock.Call
}

// CreateBookingWithSeatLock is a helper method to define mock.On call
//   - ctx context.Context
//   - onlineCustomerID int64
//   - showID int
//   - seatStatusIDs []int
//   - totalPrice float64
//   - expiresAt time.Time
//   - bookingRef string
func (_e *MockCustomerBookingRepository_Expecter) CreateBookingWithSeatLock(ctx interface{}, onlineCustomerID interface{}, showID interface{}, seatStatusIDs interface{}, totalPrice interface{}, expiresAt interface{}, bookingRef interface{}) *MockCustomerBookingRepository_CreateBookingWithSeatLock_Call {
	return &MockCustomerBookingRepository_CreateBookingWithSeatLock_Call{Call: _e.mock.On("CreateBookingWithSeatLock", ctx, onlineCustomerID, showID, seatStatusIDs, totalPrice, expiresAt, bookingRef)}
}

func (_c *MockCustomerBookingRepository_CreateBookingWithSeatLock_Call) Run(run func(ctx context.Context, onlineCustomerID int64, showID int, seatStatusIDs []int, totalPrice float64, expiresAt time.Time, bookingRef string)) *MockCustomerBookingRepository_CreateBookingWithSeatLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []int
		if args[3] != nil {
			arg3 = args[3].([]int)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockCustomerBookingRepository_CreateBookingWithSeatLock_Call) Return(booking *model.Booking, err error) *MockCustomerBookingRepository_CreateBookingWithSeatLock_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockCustomerBookingRepository_CreateBookingWithSeatLock_Call) RunAndReturn(run func(ctx context.Context, onlineCustomerID int64, showID int, seatStatusIDs []int, totalPrice float64, expiresAt time.Time, bookingRef string) (*model.Booking, error)) *MockCustomerBookingRepository_CreateBookingWithSeatLock_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingByID provides a mock function for the type MockCustomerBookingRepository
func (_mock *MockCustomerBookingRepository) GetBookingByID(ctx context.Context, bookingID int) (*model.Booking, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByID")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*model.Booking, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *model.Booking); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerBookingRepository_GetBookingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingByID'
type MockCustomerBookingRepository_GetBookingByID_Call struct {
	*mock.Call
}

// GetBookingByID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
func (_e *MockCustomerBookingRepository_Expecter) GetBookingByID(ctx interface{}, bookingID interface{}) *MockCustomerBookingRepository_GetBookingByID_Call {
	return &MockCustomerBookingRepository_GetBookingByID_Call{Call: _e.mock.On("GetBookingByID", ctx, bookingID)}
}

func (_c *MockCustomerBookingRepository_GetBookingByID_Call) Run(run func(ctx context.Context, bookingID int)) *MockCustomerBookingRepository_GetBookingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerBookingRepository_GetBookingByID_Call) Return(booking *model.Booking, err error) *MockCustomerBookingRepository_GetBookingByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockCustomerBookingRepository_GetBookingByID_Call) RunAndReturn(run func(ctx context.Context, bookingID int) (*model.Booking, error)) *MockCustomerBookingRepository_GetBookingByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeatStatusesWithSeatByIDs provides a mock function for the type MockCustomerBookingRepository
func (_mock *MockCustomerBookingRepository) GetSeatStatusesWithSeatByIDs(ctx context.Context, ids []int) ([]model.ShowSeatStatus, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetSeatStatusesWithSeatByIDs")
	}

	var r0 []model.ShowSeatStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]model.ShowSeatStatus, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []model.ShowSeatStatus); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShowSeatStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeatStatusesWithSeatByIDs'
type MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call struct {
	*mock.Call
}

// GetSeatStatusesWithSeatByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockCustomerBookingRepository_Expecter) GetSeatStatusesWithSeatByIDs(ctx interface{}, ids interface{}) *MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call {
	return &MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call{Call: _e.mock.On("GetSeatStatusesWithSeatByIDs", ctx, ids)}
}

func (_c *MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call) Run(run func(ctx context.Context, ids []int)) *MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call) Return(showSeatStatuss []model.ShowSeatStatus, err error) *MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call {
	_c.Call.Return(showSeatStatuss, err)
	return _c
}

func (_c *MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]model.ShowSeatStatus, error)) *MockCustomerBookingRepository_GetSeatStatusesWithSeatByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseExpiredBookings provides a mock function for the type MockCustomerBookingRepository
func (_mock *MockCustomerBookingRepository) ReleaseExpiredBookings(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseExpiredBookings")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerBookingRepository_ReleaseExpiredBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseExpiredBookings'
type MockCustomerBookingRepository_ReleaseExpiredBookings_Call struct {
	*mock.Call
}

// ReleaseExpiredBookings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCustomerBookingRepository_Expecter) ReleaseExpiredBookings(ctx interface{}) *MockCustomerBookingRepository_ReleaseExpiredBookings_Call {
	return &MockCustomerBookingRepository_ReleaseExpiredBookings_Call{Call: _e.mock.On("ReleaseExpiredBookings", ctx)}
}

func (_c *MockCustomerBookingRepository_ReleaseExpiredBookings_Call) Run(run func(ctx context.Context)) *MockCustomerBookingRepository_ReleaseExpiredBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerBookingRepository_ReleaseExpiredBookings_Call) Return(n int64, err error) *MockCustomerBookingRepository_ReleaseExpiredBookings_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCustomerBookingRepository_ReleaseExpiredBookings_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockCustomerBookingRepository_ReleaseExpiredBookings_Call {
	_c.Call.Return(run)
	return _c
}
