// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSeatRepository creates a new instance of MockSeatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeatRepository {
	mock := &MockSeatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSeatRepository is an autogenerated mock type for the SeatRepository type
type MockSeatRepository struct {
	mock.Mock
}

type MockSeatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeatRepository) EXPECT() *MockSeatRepository_Expecter {
	return &MockSeatRepository_Expecter{mock: &_m.Mock}
}

// CreateSeat provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) CreateSeat(ctx context.Context, seat *model.Seat) error {
	ret := _mock.Called(ctx, seat)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Seat) error); ok {
		r0 = returnFunc(ctx, seat)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeatRepository_CreateSeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeat'
type MockSeatRepository_CreateSeat_Call struct {
	*mock.Call
}

// CreateSeat is a helper method to define mock.On call
//   - ctx context.Context
//   - seat *model.Seat
func (_e *MockSeatRepository_Expecter) CreateSeat(ctx interface{}, seat interface{}) *MockSeatRepository_CreateSeat_Call {
	return &MockSeatRepository_CreateSeat_Call{Call: _e.mock.On("CreateSeat", ctx, seat)}
}

func (_c *MockSeatRepository_CreateSeat_Call) Run(run func(ctx context.Context, seat *model.Seat)) *MockSeatRepository_CreateSeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Seat
		if args[1] != nil {
			arg1 = args[1].(*model.Seat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_CreateSeat_Call) Return(err error) *MockSeatRepository_CreateSeat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeatRepository_CreateSeat_Call) RunAndReturn(run func(ctx context.Context, seat *model.Seat) error) *MockSeatRepository_CreateSeat_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShow provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) CreateShow(ctx context.Context, show *model.Show) error {
	ret := _mock.Called(ctx, show)

	if len(ret) == 0 {
		panic("no return value specified for CreateShow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Show) error); ok {
		r0 = returnFunc(ctx, show)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeatRepository_CreateShow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShow'
type MockSeatRepository_CreateShow_Call struct {
	*mock.Call
}

// CreateShow is a helper method to define mock.On call
//   - ctx context.Context
//   - show *model.Show
func (_e *MockSeatRepository_Expecter) CreateShow(ctx interface{}, show interface{}) *MockSeatRepository_CreateShow_Call {
	return &MockSeatRepository_CreateShow_Call{Call: _e.mock.On("CreateShow", ctx, show)}
}

func (_c *MockSeatRepository_CreateShow_Call) Run(run func(ctx context.Context, show *model.Show)) *MockSeatRepository_CreateShow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Show
		if args[1] != nil {
			arg1 = args[1].(*model.Show)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_CreateShow_Call) Return(err error) *MockSeatRepository_CreateShow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeatRepository_CreateShow_Call) RunAndReturn(run func(ctx context.Context, show *model.Show) error) *MockSeatRepository_CreateShow_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShowPricing provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) CreateShowPricing(ctx context.Context, pricing *model.ShowPricing) error {
	ret := _mock.Called(ctx, pricing)

	if len(ret) == 0 {
		panic("no return value specified for CreateShowPricing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ShowPricing) error); ok {
		r0 = returnFunc(ctx, pricing)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeatRepository_CreateShowPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShowPricing'
type MockSeatRepository_CreateShowPricing_Call struct {
	*mock.Call
}

// CreateShowPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - pricing *model.ShowPricing
func (_e *MockSeatRepository_Expecter) CreateShowPricing(ctx interface{}, pricing interface{}) *MockSeatRepository_CreateShowPricing_Call {
	return &MockSeatRepository_CreateShowPricing_Call{Call: _e.mock.On("CreateShowPricing", ctx, pricing)}
}

func (_c *MockSeatRepository_CreateShowPricing_Call) Run(run func(ctx context.Context, pricing *model.ShowPricing)) *MockSeatRepository_CreateShowPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ShowPricing
		if args[1] != nil {
			arg1 = args[1].(*model.ShowPricing)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_CreateShowPricing_Call) Return(err error) *MockSeatRepository_CreateShowPricing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeatRepository_CreateShowPricing_Call) RunAndReturn(run func(ctx context.Context, pricing *model.ShowPricing) error) *MockSeatRepository_CreateShowPricing_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShowSeatStatus provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) CreateShowSeatStatus(ctx context.Context, sss *model.ShowSeatStatus) error {
	ret := _mock.Called(ctx, sss)

	if len(ret) == 0 {
		panic("no return value specified for CreateShowSeatStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ShowSeatStatus) error); ok {
		r0 = returnFunc(ctx, sss)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeatRepository_CreateShowSeatStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShowSeatStatus'
type MockSeatRepository_CreateShowSeatStatus_Call struct {
	*mock.Call
}

// CreateShowSeatStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - sss *model.ShowSeatStatus
func (_e *MockSeatRepository_Expecter) CreateShowSeatStatus(ctx interface{}, sss interface{}) *MockSeatRepository_CreateShowSeatStatus_Call {
	return &MockSeatRepository_CreateShowSeatStatus_Call{Call: _e.mock.On("CreateShowSeatStatus", ctx, sss)}
}

func (_c *MockSeatRepository_CreateShowSeatStatus_Call) Run(run func(ctx context.Context, sss *model.ShowSeatStatus)) *MockSeatRepository_CreateShowSeatStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ShowSeatStatus
		if args[1] != nil {
			arg1 = args[1].(*model.ShowSeatStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_CreateShowSeatStatus_Call) Return(err error) *MockSeatRepository_CreateShowSeatStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeatRepository_CreateShowSeatStatus_Call) RunAndReturn(run func(ctx context.Context, sss *model.ShowSeatStatus) error) *MockSeatRepository_CreateShowSeatStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindPricingByShowID provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) FindPricingByShowID(ctx context.Context, showID int) ([]model.ShowPricing, error) {
	ret := _mock.Called(ctx, showID)

	if len(ret) == 0 {
		panic("no return value specified for FindPricingByShowID")
	}

	var r0 []model.ShowPricing
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model.ShowPricing, error)); ok {
		return returnFunc(ctx, showID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model.ShowPricing); ok {
		r0 = returnFunc(ctx, showID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShowPricing)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, showID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_FindPricingByShowID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPricingByShowID'
type MockSeatRepository_FindPricingByShowID_Call struct {
	*mock.Call
}

// FindPricingByShowID is a helper method to define mock.On call
//   - ctx context.Context
//   - showID int
func (_e *MockSeatRepository_Expecter) FindPricingByShowID(ctx interface{}, showID interface{}) *MockSeatRepository_FindPricingByShowID_Call {
	return &MockSeatRepository_FindPricingByShowID_Call{Call: _e.mock.On("FindPricingByShowID", ctx, showID)}
}

func (_c *MockSeatRepository_FindPricingByShowID_Call) Run(run func(ctx context.Context, showID int)) *MockSeatRepository_FindPricingByShowID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_FindPricingByShowID_Call) Return(showPricings []model.ShowPricing, err error) *MockSeatRepository_FindPricingByShowID_Call {
	_c.Call.Return(showPricings, err)
	return _c
}

func (_c *MockSeatRepository_FindPricingByShowID_Call) RunAndReturn(run func(ctx context.Context, showID int) ([]model.ShowPricing, error)) *MockSeatRepository_FindPricingByShowID_Call {
	_c.Call.Return(run)
	return _c
}

// FindScreenByName provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) FindScreenByName(ctx context.Context, name string) (*model.Screen, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindScreenByName")
	}

	var r0 *model.Screen
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Screen, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Screen); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Screen)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_FindScreenByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindScreenByName'
type MockSeatRepository_FindScreenByName_Call struct {
	*mock.Call
}

// FindScreenByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSeatRepository_Expecter) FindScreenByName(ctx interface{}, name interface{}) *MockSeatRepository_FindScreenByName_Call {
	return &MockSeatRepository_FindScreenByName_Call{Call: _e.mock.On("FindScreenByName", ctx, name)}
}

func (_c *MockSeatRepository_FindScreenByName_Call) Run(run func(ctx context.Context, name string)) *MockSeatRepository_FindScreenByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_FindScreenByName_Call) Return(screen *model.Screen, err error) *MockSeatRepository_FindScreenByName_Call {
	_c.Call.Return(screen, err)
	return _c
}

func (_c *MockSeatRepository_FindScreenByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Screen, error)) *MockSeatRepository_FindScreenByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindSeatStatusByShowID provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) FindSeatStatusByShowID(ctx context.Context, showID int) ([]model.ShowSeatStatus, error) {
	ret := _mock.Called(ctx, showID)

	if len(ret) == 0 {
		panic("no return value specified for FindSeatStatusByShowID")
	}

	var r0 []model.ShowSeatStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model.ShowSeatStatus, error)); ok {
		return returnFunc(ctx, showID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model.ShowSeatStatus); ok {
		r0 = returnFunc(ctx, showID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShowSeatStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, showID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_FindSeatStatusByShowID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSeatStatusByShowID'
type MockSeatRepository_FindSeatStatusByShowID_Call struct {
	*mock.Call
}

// FindSeatStatusByShowID is a helper method to define mock.On call
//   - ctx context.Context
//   - showID int
func (_e *MockSeatRepository_Expecter) FindSeatStatusByShowID(ctx interface{}, showID interface{}) *MockSeatRepository_FindSeatStatusByShowID_Call {
	return &MockSeatRepository_FindSeatStatusByShowID_Call{Call: _e.mock.On("FindSeatStatusByShowID", ctx, showID)}
}

func (_c *MockSeatRepository_FindSeatStatusByShowID_Call) Run(run func(ctx context.Context, showID int)) *MockSeatRepository_FindSeatStatusByShowID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_FindSeatStatusByShowID_Call) Return(showSeatStatuss []model.ShowSeatStatus, err error) *MockSeatRepository_FindSeatStatusByShowID_Call {
	_c.Call.Return(showSeatStatuss, err)
	return _c
}

func (_c *MockSeatRepository_FindSeatStatusByShowID_Call) RunAndReturn(run func(ctx context.Context, showID int) ([]model.ShowSeatStatus, error)) *MockSeatRepository_FindSeatStatusByShowID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSeatsByScreenID provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) FindSeatsByScreenID(ctx context.Context, screenID int) ([]model.Seat, error) {
	ret := _mock.Called(ctx, screenID)

	if len(ret) == 0 {
		panic("no return value specified for FindSeatsByScreenID")
	}

	var r0 []model.Seat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model.Seat, error)); ok {
		return returnFunc(ctx, screenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model.Seat); ok {
		r0 = returnFunc(ctx, screenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Seat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, screenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_FindSeatsByScreenID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSeatsByScreenID'
type MockSeatRepository_FindSeatsByScreenID_Call struct {
	*mock.Call
}

// FindSeatsByScreenID is a helper method to define mock.On call
//   - ctx context.Context
//   - screenID int
func (_e *MockSeatRepository_Expecter) FindSeatsByScreenID(ctx interface{}, screenID interface{}) *MockSeatRepository_FindSeatsByScreenID_Call {
	return &MockSeatRepository_FindSeatsByScreenID_Call{Call: _e.mock.On("FindSeatsByScreenID", ctx, screenID)}
}

func (_c *MockSeatRepository_FindSeatsByScreenID_Call) Run(run func(ctx context.Context, screenID int)) *MockSeatRepository_FindSeatsByScreenID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_FindSeatsByScreenID_Call) Return(seats []model.Seat, err error) *MockSeatRepository_FindSeatsByScreenID_Call {
	_c.Call.Return(seats, err)
	return _c
}

func (_c *MockSeatRepository_FindSeatsByScreenID_Call) RunAndReturn(run func(ctx context.Context, screenID int) ([]model.Seat, error)) *MockSeatRepository_FindSeatsByScreenID_Call {
	_c.Call.Return(run)
	return _c
}

// FindShowByScreenAndMovie provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) FindShowByScreenAndMovie(ctx context.Context, screenID int, movieID string) (*model.Show, error) {
	ret := _mock.Called(ctx, screenID, movieID)

	if len(ret) == 0 {
		panic("no return value specified for FindShowByScreenAndMovie")
	}

	var r0 *model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (*model.Show, error)); ok {
		return returnFunc(ctx, screenID, movieID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) *model.Show); ok {
		r0 = returnFunc(ctx, screenID, movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, screenID, movieID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_FindShowByScreenAndMovie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindShowByScreenAndMovie'
type MockSeatRepository_FindShowByScreenAndMovie_Call struct {
	*mock.Call
}

// FindShowByScreenAndMovie is a helper method to define mock.On call
//   - ctx context.Context
//   - screenID int
//   - movieID string
func (_e *MockSeatRepository_Expecter) FindShowByScreenAndMovie(ctx interface{}, screenID interface{}, movieID interface{}) *MockSeatRepository_FindShowByScreenAndMovie_Call {
	return &MockSeatRepository_FindShowByScreenAndMovie_Call{Call: _e.mock.On("FindShowByScreenAndMovie", ctx, screenID, movieID)}
}

func (_c *MockSeatRepository_FindShowByScreenAndMovie_Call) Run(run func(ctx context.Context, screenID int, movieID string)) *MockSeatRepository_FindShowByScreenAndMovie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSeatRepository_FindShowByScreenAndMovie_Call) Return(show *model.Show, err error) *MockSeatRepository_FindShowByScreenAndMovie_Call {
	_c.Call.Return(show, err)
	return _c
}

func (_c *MockSeatRepository_FindShowByScreenAndMovie_Call) RunAndReturn(run func(ctx context.Context, screenID int, movieID string) (*model.Show, error)) *MockSeatRepository_FindShowByScreenAndMovie_Call {
	_c.Call.Return(run)
	return _c
}

// FindShowsByScreenID provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) FindShowsByScreenID(ctx context.Context, screenID int) ([]model.Show, error) {
	ret := _mock.Called(ctx, screenID)

	if len(ret) == 0 {
		panic("no return value specified for FindShowsByScreenID")
	}

	var r0 []model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model.Show, error)); ok {
		return returnFunc(ctx, screenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model.Show); ok {
		r0 = returnFunc(ctx, screenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, screenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_FindShowsByScreenID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindShowsByScreenID'
type MockSeatRepository_FindShowsByScreenID_Call struct {
	*mock.Call
}

// FindShowsByScreenID is a helper method to define mock.On call
//   - ctx context.Context
//   - screenID int
func (_e *MockSeatRepository_Expecter) FindShowsByScreenID(ctx interface{}, screenID interface{}) *MockSeatRepository_FindShowsByScreenID_Call {
	return &MockSeatRepository_FindShowsByScreenID_Call{Call: _e.mock.On("FindShowsByScreenID", ctx, screenID)}
}

func (_c *MockSeatRepository_FindShowsByScreenID_Call) Run(run func(ctx context.Context, screenID int)) *MockSeatRepository_FindShowsByScreenID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_FindShowsByScreenID_Call) Return(shows []model.Show, err error) *MockSeatRepository_FindShowsByScreenID_Call {
	_c.Call.Return(shows, err)
	return _c
}

func (_c *MockSeatRepository_FindShowsByScreenID_Call) RunAndReturn(run func(ctx context.Context, screenID int) ([]model.Show, error)) *MockSeatRepository_FindShowsByScreenID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPricingByShowID provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) GetPricingByShowID(ctx context.Context, showID uint) ([]model.ShowPricing, error) {
	ret := _mock.Called(ctx, showID)

	if len(ret) == 0 {
		panic("no return value specified for GetPricingByShowID")
	}

	var r0 []model.ShowPricing
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]model.ShowPricing, error)); ok {
		return returnFunc(ctx, showID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []model.ShowPricing); ok {
		r0 = returnFunc(ctx, showID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShowPricing)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, showID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_GetPricingByShowID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricingByShowID'
type MockSeatRepository_GetPricingByShowID_Call struct {
	*mock.Call
}

// GetPricingByShowID is a helper method to define mock.On call
//   - ctx context.Context
//   - showID uint
func (_e *MockSeatRepository_Expecter) GetPricingByShowID(ctx interface{}, showID interface{}) *MockSeatRepository_GetPricingByShowID_Call {
	return &MockSeatRepository_GetPricingByShowID_Call{Call: _e.mock.On("GetPricingByShowID", ctx, showID)}
}

func (_c *MockSeatRepository_GetPricingByShowID_Call) Run(run func(ctx context.Context, showID uint)) *MockSeatRepository_GetPricingByShowID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_GetPricingByShowID_Call) Return(showPricings []model.ShowPricing, err error) *MockSeatRepository_GetPricingByShowID_Call {
	_c.Call.Return(showPricings, err)
	return _c
}

func (_c *MockSeatRepository_GetPricingByShowID_Call) RunAndReturn(run func(ctx context.Context, showID uint) ([]model.ShowPricing, error)) *MockSeatRepository_GetPricingByShowID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeatStatusByShowID provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) GetSeatStatusByShowID(ctx context.Context, showID uint) ([]model.ShowSeatStatus, error) {
	ret := _mock.Called(ctx, showID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeatStatusByShowID")
	}

	var r0 []model.ShowSeatStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]model.ShowSeatStatus, error)); ok {
		return returnFunc(ctx, showID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []model.ShowSeatStatus); ok {
		r0 = returnFunc(ctx, showID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShowSeatStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, showID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_GetSeatStatusByShowID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeatStatusByShowID'
type MockSeatRepository_GetSeatStatusByShowID_Call struct {
	*mock.Call
}

// GetSeatStatusByShowID is a helper method to define mock.On call
//   - ctx context.Context
//   - showID uint
func (_e *MockSeatRepository_Expecter) GetSeatStatusByShowID(ctx interface{}, showID interface{}) *MockSeatRepository_GetSeatStatusByShowID_Call {
	return &MockSeatRepository_GetSeatStatusByShowID_Call{Call: _e.mock.On("GetSeatStatusByShowID", ctx, showID)}
}

func (_c *MockSeatRepository_GetSeatStatusByShowID_Call) Run(run func(ctx context.Context, showID uint)) *MockSeatRepository_GetSeatStatusByShowID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_GetSeatStatusByShowID_Call) Return(showSeatStatuss []model.ShowSeatStatus, err error) *MockSeatRepository_GetSeatStatusByShowID_Call {
	_c.Call.Return(showSeatStatuss, err)
	return _c
}

func (_c *MockSeatRepository_GetSeatStatusByShowID_Call) RunAndReturn(run func(ctx context.Context, showID uint) ([]model.ShowSeatStatus, error)) *MockSeatRepository_GetSeatStatusByShowID_Call {
	_c.Call.Return(run)
	return _c
}

// GetShowByID provides a mock function for the type MockSeatRepository
func (_mock *MockSeatRepository) GetShowByID(ctx context.Context, showID uint) (*model.Show, error) {
	ret := _mock.Called(ctx, showID)

	if len(ret) == 0 {
		panic("no return value specified for GetShowByID")
	}

	var r0 *model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*model.Show, error)); ok {
		return returnFunc(ctx, showID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *model.Show); ok {
		r0 = returnFunc(ctx, showID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, showID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatRepository_GetShowByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShowByID'
type MockSeatRepository_GetShowByID_Call struct {
	*mock.Call
}

// GetShowByID is a helper method to define mock.On call
//   - ctx context.Context
//   - showID uint
func (_e *MockSeatRepository_Expecter) GetShowByID(ctx interface{}, showID interface{}) *MockSeatRepository_GetShowByID_Call {
	return &MockSeatRepository_GetShowByID_Call{Call: _e.mock.On("GetShowByID", ctx, showID)}
}

func (_c *MockSeatRepository_GetShowByID_Call) Run(run func(ctx context.Context, showID uint)) *MockSeatRepository_GetShowByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatRepository_GetShowByID_Call) Return(show *model.Show, err error) *MockSeatRepository_GetShowByID_Call {
	_c.Call.Return(show, err)
	return _c
}

func (_c *MockSeatRepository_GetShowByID_Call) RunAndReturn(run func(ctx context.Context, showID uint) (*model.Show, error)) *MockSeatRepository_GetShowByID_Call {
	_c.Call.Return(run)
	return _c
}
