// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProfilePictureRepository creates a new instance of MockProfilePictureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfilePictureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfilePictureRepository {
	mock := &MockProfilePictureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfilePictureRepository is an autogenerated mock type for the ProfilePictureRepository type
type MockProfilePictureRepository struct {
	mock.Mock
}

type MockProfilePictureRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfilePictureRepository) EXPECT() *MockProfilePictureRepository_Expecter {
	return &MockProfilePictureRepository_Expecter{mock: &_m.Mock}
}

// DeleteByUserID provides a mock function for the type MockProfilePictureRepository
func (_mock *MockProfilePictureRepository) DeleteByUserID(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfilePictureRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockProfilePictureRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockProfilePictureRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockProfilePictureRepository_DeleteByUserID_Call {
	return &MockProfilePictureRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockProfilePictureRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockProfilePictureRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfilePictureRepository_DeleteByUserID_Call) Return(err error) *MockProfilePictureRepository_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfilePictureRepository_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockProfilePictureRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockProfilePictureRepository
func (_mock *MockProfilePictureRepository) GetByUserID(ctx context.Context, userID uint) (*model.ProfilePicture, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.ProfilePicture
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*model.ProfilePicture, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *model.ProfilePicture); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProfilePicture)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfilePictureRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockProfilePictureRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockProfilePictureRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockProfilePictureRepository_GetByUserID_Call {
	return &MockProfilePictureRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockProfilePictureRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockProfilePictureRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfilePictureRepository_GetByUserID_Call) Return(profilePicture *model.ProfilePicture, err error) *MockProfilePictureRepository_GetByUserID_Call {
	_c.Call.Return(profilePicture, err)
	return _c
}

func (_c *MockProfilePictureRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*model.ProfilePicture, error)) *MockProfilePictureRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockProfilePictureRepository
func (_mock *MockProfilePictureRepository) Upsert(ctx context.Context, pic model.ProfilePicture) error {
	ret := _mock.Called(ctx, pic)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ProfilePicture) error); ok {
		r0 = returnFunc(ctx, pic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfilePictureRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockProfilePictureRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - pic model.ProfilePicture
func (_e *MockProfilePictureRepository_Expecter) Upsert(ctx interface{}, pic interface{}) *MockProfilePictureRepository_Upsert_Call {
	return &MockProfilePictureRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, pic)}
}

func (_c *MockProfilePictureRepository_Upsert_Call) Run(run func(ctx context.Context, pic model.ProfilePicture)) *MockProfilePictureRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ProfilePicture
		if args[1] != nil {
			arg1 = args[1].(model.ProfilePicture)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfilePictureRepository_Upsert_Call) Return(err error) *MockProfilePictureRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfilePictureRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, pic model.ProfilePicture) error) *MockProfilePictureRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
