// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// newMockgormProvider creates a new instance of mockgormProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgormProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgormProvider {
	mock := &mockgormProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgormProvider is an autogenerated mock type for the gormProvider type
type mockgormProvider struct {
	mock.Mock
}

type mockgormProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgormProvider) EXPECT() *mockgormProvider_Expecter {
	return &mockgormProvider_Expecter{mock: &_m.Mock}
}

// GormDB provides a mock function for the type mockgormProvider
func (_mock *mockgormProvider) GormDB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GormDB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// mockgormProvider_GormDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GormDB'
type mockgormProvider_GormDB_Call struct {
	*mock.Call
}

// GormDB is a helper method to define mock.On call
func (_e *mockgormProvider_Expecter) GormDB() *mockgormProvider_GormDB_Call {
	return &mockgormProvider_GormDB_Call{Call: _e.mock.On("GormDB")}
}

func (_c *mockgormProvider_GormDB_Call) Run(run func()) *mockgormProvider_GormDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgormProvider_GormDB_Call) Return(dB *gorm.DB) *mockgormProvider_GormDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *mockgormProvider_GormDB_Call) RunAndReturn(run func() *gorm.DB) *mockgormProvider_GormDB_Call {
	_c.Call.Return(run)
	return _c
}
