CREATE TABLE IF NOT EXISTS profile_pictures (
    id          BIGSERIAL PRIMARY KEY,
    user_id     INTEGER NOT NULL UNIQUE REFERENCES customer(id) ON DELETE CASCADE,
    image_data  TEXT NOT NULL,
    content_type VARCHAR(50) NOT NULL DEFAULT 'image/jpeg',
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);