// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/request"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAvatarService creates a new instance of MockAvatarService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarService {
	mock := &MockAvatarService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAvatarService is an autogenerated mock type for the AvatarService type
type MockAvatarService struct {
	mock.Mock
}

type MockAvatarService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarService) EXPECT() *MockAvatarService_Expecter {
	return &MockAvatarService_Expecter{mock: &_m.Mock}
}

// AssignRandomAvatar provides a mock function for the type MockAvatarService
func (_mock *MockAvatarService) AssignRandomAvatar(ctx context.Context, userID uint, gender string) (*response.AvatarResponse, error) {
	ret := _mock.Called(ctx, userID, gender)

	if len(ret) == 0 {
		panic("no return value specified for AssignRandomAvatar")
	}

	var r0 *response.AvatarResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (*response.AvatarResponse, error)); ok {
		return returnFunc(ctx, userID, gender)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) *response.AvatarResponse); ok {
		r0 = returnFunc(ctx, userID, gender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AvatarResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, gender)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarService_AssignRandomAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRandomAvatar'
type MockAvatarService_AssignRandomAvatar_Call struct {
	*mock.Call
}

// AssignRandomAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - gender string
func (_e *MockAvatarService_Expecter) AssignRandomAvatar(ctx interface{}, userID interface{}, gender interface{}) *MockAvatarService_AssignRandomAvatar_Call {
	return &MockAvatarService_AssignRandomAvatar_Call{Call: _e.mock.On("AssignRandomAvatar", ctx, userID, gender)}
}

func (_c *MockAvatarService_AssignRandomAvatar_Call) Run(run func(ctx context.Context, userID uint, gender string)) *MockAvatarService_AssignRandomAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAvatarService_AssignRandomAvatar_Call) Return(avatarResponse *response.AvatarResponse, err error) *MockAvatarService_AssignRandomAvatar_Call {
	_c.Call.Return(avatarResponse, err)
	return _c
}

func (_c *MockAvatarService_AssignRandomAvatar_Call) RunAndReturn(run func(ctx context.Context, userID uint, gender string) (*response.AvatarResponse, error)) *MockAvatarService_AssignRandomAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAvatar provides a mock function for the type MockAvatarService
func (_mock *MockAvatarService) GetUserAvatar(ctx context.Context, userID uint) (*response.AvatarResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAvatar")
	}

	var r0 *response.AvatarResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*response.AvatarResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *response.AvatarResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AvatarResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarService_GetUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAvatar'
type MockAvatarService_GetUserAvatar_Call struct {
	*mock.Call
}

// GetUserAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockAvatarService_Expecter) GetUserAvatar(ctx interface{}, userID interface{}) *MockAvatarService_GetUserAvatar_Call {
	return &MockAvatarService_GetUserAvatar_Call{Call: _e.mock.On("GetUserAvatar", ctx, userID)}
}

func (_c *MockAvatarService_GetUserAvatar_Call) Run(run func(ctx context.Context, userID uint)) *MockAvatarService_GetUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarService_GetUserAvatar_Call) Return(avatarResponse *response.AvatarResponse, err error) *MockAvatarService_GetUserAvatar_Call {
	_c.Call.Return(avatarResponse, err)
	return _c
}

func (_c *MockAvatarService_GetUserAvatar_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*response.AvatarResponse, error)) *MockAvatarService_GetUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// ListPredefinedAvatars provides a mock function for the type MockAvatarService
func (_mock *MockAvatarService) ListPredefinedAvatars(ctx context.Context, gender string) (*response.PredefinedAvatarListResponse, error) {
	ret := _mock.Called(ctx, gender)

	if len(ret) == 0 {
		panic("no return value specified for ListPredefinedAvatars")
	}

	var r0 *response.PredefinedAvatarListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*response.PredefinedAvatarListResponse, error)); ok {
		return returnFunc(ctx, gender)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *response.PredefinedAvatarListResponse); ok {
		r0 = returnFunc(ctx, gender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PredefinedAvatarListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, gender)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarService_ListPredefinedAvatars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPredefinedAvatars'
type MockAvatarService_ListPredefinedAvatars_Call struct {
	*mock.Call
}

// ListPredefinedAvatars is a helper method to define mock.On call
//   - ctx context.Context
//   - gender string
func (_e *MockAvatarService_Expecter) ListPredefinedAvatars(ctx interface{}, gender interface{}) *MockAvatarService_ListPredefinedAvatars_Call {
	return &MockAvatarService_ListPredefinedAvatars_Call{Call: _e.mock.On("ListPredefinedAvatars", ctx, gender)}
}

func (_c *MockAvatarService_ListPredefinedAvatars_Call) Run(run func(ctx context.Context, gender string)) *MockAvatarService_ListPredefinedAvatars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarService_ListPredefinedAvatars_Call) Return(predefinedAvatarListResponse *response.PredefinedAvatarListResponse, err error) *MockAvatarService_ListPredefinedAvatars_Call {
	_c.Call.Return(predefinedAvatarListResponse, err)
	return _c
}

func (_c *MockAvatarService_ListPredefinedAvatars_Call) RunAndReturn(run func(ctx context.Context, gender string) (*response.PredefinedAvatarListResponse, error)) *MockAvatarService_ListPredefinedAvatars_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAvatar provides a mock function for the type MockAvatarService
func (_mock *MockAvatarService) UpdateAvatar(ctx context.Context, userID uint, req request.UpdateAvatarRequest) (*response.AvatarResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatar")
	}

	var r0 *response.AvatarResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, request.UpdateAvatarRequest) (*response.AvatarResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, request.UpdateAvatarRequest) *response.AvatarResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AvatarResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, request.UpdateAvatarRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarService_UpdateAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAvatar'
type MockAvatarService_UpdateAvatar_Call struct {
	*mock.Call
}

// UpdateAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - req request.UpdateAvatarRequest
func (_e *MockAvatarService_Expecter) UpdateAvatar(ctx interface{}, userID interface{}, req interface{}) *MockAvatarService_UpdateAvatar_Call {
	return &MockAvatarService_UpdateAvatar_Call{Call: _e.mock.On("UpdateAvatar", ctx, userID, req)}
}

func (_c *MockAvatarService_UpdateAvatar_Call) Run(run func(ctx context.Context, userID uint, req request.UpdateAvatarRequest)) *MockAvatarService_UpdateAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 request.UpdateAvatarRequest
		if args[2] != nil {
			arg2 = args[2].(request.UpdateAvatarRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAvatarService_UpdateAvatar_Call) Return(avatarResponse *response.AvatarResponse, err error) *MockAvatarService_UpdateAvatar_Call {
	_c.Call.Return(avatarResponse, err)
	return _c
}

func (_c *MockAvatarService_UpdateAvatar_Call) RunAndReturn(run func(ctx context.Context, userID uint, req request.UpdateAvatarRequest) (*response.AvatarResponse, error)) *MockAvatarService_UpdateAvatar_Call {
	_c.Call.Return(run)
	return _c
}
