// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/request"
	"skyfox/bookings/dto/response"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminScheduleService creates a new instance of MockAdminScheduleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminScheduleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminScheduleService {
	mock := &MockAdminScheduleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminScheduleService is an autogenerated mock type for the AdminScheduleService type
type MockAdminScheduleService struct {
	mock.Mock
}

type MockAdminScheduleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminScheduleService) EXPECT() *MockAdminScheduleService_Expecter {
	return &MockAdminScheduleService_Expecter{mock: &_m.Mock}
}

// AddScreen provides a mock function for the type MockAdminScheduleService
func (_mock *MockAdminScheduleService) AddScreen(ctx context.Context, req request.AddScreenRequest) (*response.ScreenOption, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddScreen")
	}

	var r0 *response.ScreenOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.AddScreenRequest) (*response.ScreenOption, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.AddScreenRequest) *response.ScreenOption); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ScreenOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.AddScreenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleService_AddScreen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddScreen'
type MockAdminScheduleService_AddScreen_Call struct {
	*mock.Call
}

// AddScreen is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.AddScreenRequest
func (_e *MockAdminScheduleService_Expecter) AddScreen(ctx interface{}, req interface{}) *MockAdminScheduleService_AddScreen_Call {
	return &MockAdminScheduleService_AddScreen_Call{Call: _e.mock.On("AddScreen", ctx, req)}
}

func (_c *MockAdminScheduleService_AddScreen_Call) Run(run func(ctx context.Context, req request.AddScreenRequest)) *MockAdminScheduleService_AddScreen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.AddScreenRequest
		if args[1] != nil {
			arg1 = args[1].(request.AddScreenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminScheduleService_AddScreen_Call) Return(screenOption *response.ScreenOption, err error) *MockAdminScheduleService_AddScreen_Call {
	_c.Call.Return(screenOption, err)
	return _c
}

func (_c *MockAdminScheduleService_AddScreen_Call) RunAndReturn(run func(ctx context.Context, req request.AddScreenRequest) (*response.ScreenOption, error)) *MockAdminScheduleService_AddScreen_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteShow provides a mock function for the type MockAdminScheduleService
func (_mock *MockAdminScheduleService) DeleteShow(ctx context.Context, showID int) error {
	ret := _mock.Called(ctx, showID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, showID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminScheduleService_DeleteShow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteShow'
type MockAdminScheduleService_DeleteShow_Call struct {
	*mock.Call
}

// DeleteShow is a helper method to define mock.On call
//   - ctx context.Context
//   - showID int
func (_e *MockAdminScheduleService_Expecter) DeleteShow(ctx interface{}, showID interface{}) *MockAdminScheduleService_DeleteShow_Call {
	return &MockAdminScheduleService_DeleteShow_Call{Call: _e.mock.On("DeleteShow", ctx, showID)}
}

func (_c *MockAdminScheduleService_DeleteShow_Call) Run(run func(ctx context.Context, showID int)) *MockAdminScheduleService_DeleteShow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminScheduleService_DeleteShow_Call) Return(err error) *MockAdminScheduleService_DeleteShow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminScheduleService_DeleteShow_Call) RunAndReturn(run func(ctx context.Context, showID int) error) *MockAdminScheduleService_DeleteShow_Call {
	_c.Call.Return(run)
	return _c
}

// GetScreens provides a mock function for the type MockAdminScheduleService
func (_mock *MockAdminScheduleService) GetScreens(ctx context.Context) ([]response.ScreenOption, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetScreens")
	}

	var r0 []response.ScreenOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]response.ScreenOption, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []response.ScreenOption); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.ScreenOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleService_GetScreens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScreens'
type MockAdminScheduleService_GetScreens_Call struct {
	*mock.Call
}

// GetScreens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminScheduleService_Expecter) GetScreens(ctx interface{}) *MockAdminScheduleService_GetScreens_Call {
	return &MockAdminScheduleService_GetScreens_Call{Call: _e.mock.On("GetScreens", ctx)}
}

func (_c *MockAdminScheduleService_GetScreens_Call) Run(run func(ctx context.Context)) *MockAdminScheduleService_GetScreens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminScheduleService_GetScreens_Call) Return(screenOptions []response.ScreenOption, err error) *MockAdminScheduleService_GetScreens_Call {
	_c.Call.Return(screenOptions, err)
	return _c
}

func (_c *MockAdminScheduleService_GetScreens_Call) RunAndReturn(run func(ctx context.Context) ([]response.ScreenOption, error)) *MockAdminScheduleService_GetScreens_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlots provides a mock function for the type MockAdminScheduleService
func (_mock *MockAdminScheduleService) GetSlots(ctx context.Context) ([]model.Slot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSlots")
	}

	var r0 []model.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Slot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Slot); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleService_GetSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlots'
type MockAdminScheduleService_GetSlots_Call struct {
	*mock.Call
}

// GetSlots is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminScheduleService_Expecter) GetSlots(ctx interface{}) *MockAdminScheduleService_GetSlots_Call {
	return &MockAdminScheduleService_GetSlots_Call{Call: _e.mock.On("GetSlots", ctx)}
}

func (_c *MockAdminScheduleService_GetSlots_Call) Run(run func(ctx context.Context)) *MockAdminScheduleService_GetSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminScheduleService_GetSlots_Call) Return(slots []model.Slot, err error) *MockAdminScheduleService_GetSlots_Call {
	_c.Call.Return(slots, err)
	return _c
}

func (_c *MockAdminScheduleService_GetSlots_Call) RunAndReturn(run func(ctx context.Context) ([]model.Slot, error)) *MockAdminScheduleService_GetSlots_Call {
	_c.Call.Return(run)
	return _c
}

// GetWeeklySchedule provides a mock function for the type MockAdminScheduleService
func (_mock *MockAdminScheduleService) GetWeeklySchedule(ctx context.Context, startDate string) (*response.WeeklyScheduleResponse, error) {
	ret := _mock.Called(ctx, startDate)

	if len(ret) == 0 {
		panic("no return value specified for GetWeeklySchedule")
	}

	var r0 *response.WeeklyScheduleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*response.WeeklyScheduleResponse, error)); ok {
		return returnFunc(ctx, startDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *response.WeeklyScheduleResponse); ok {
		r0 = returnFunc(ctx, startDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.WeeklyScheduleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, startDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleService_GetWeeklySchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeeklySchedule'
type MockAdminScheduleService_GetWeeklySchedule_Call struct {
	*mock.Call
}

// GetWeeklySchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate string
func (_e *MockAdminScheduleService_Expecter) GetWeeklySchedule(ctx interface{}, startDate interface{}) *MockAdminScheduleService_GetWeeklySchedule_Call {
	return &MockAdminScheduleService_GetWeeklySchedule_Call{Call: _e.mock.On("GetWeeklySchedule", ctx, startDate)}
}

func (_c *MockAdminScheduleService_GetWeeklySchedule_Call) Run(run func(ctx context.Context, startDate string)) *MockAdminScheduleService_GetWeeklySchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminScheduleService_GetWeeklySchedule_Call) Return(weeklyScheduleResponse *response.WeeklyScheduleResponse, err error) *MockAdminScheduleService_GetWeeklySchedule_Call {
	_c.Call.Return(weeklyScheduleResponse, err)
	return _c
}

func (_c *MockAdminScheduleService_GetWeeklySchedule_Call) RunAndReturn(run func(ctx context.Context, startDate string) (*response.WeeklyScheduleResponse, error)) *MockAdminScheduleService_GetWeeklySchedule_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleShow provides a mock function for the type MockAdminScheduleService
func (_mock *MockAdminScheduleService) ScheduleShow(ctx context.Context, req request.ScheduleShowRequest) (*response.ScheduleShowResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleShow")
	}

	var r0 *response.ScheduleShowResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.ScheduleShowRequest) (*response.ScheduleShowResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.ScheduleShowRequest) *response.ScheduleShowResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ScheduleShowResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.ScheduleShowRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleService_ScheduleShow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleShow'
type MockAdminScheduleService_ScheduleShow_Call struct {
	*mock.Call
}

// ScheduleShow is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.ScheduleShowRequest
func (_e *MockAdminScheduleService_Expecter) ScheduleShow(ctx interface{}, req interface{}) *MockAdminScheduleService_ScheduleShow_Call {
	return &MockAdminScheduleService_ScheduleShow_Call{Call: _e.mock.On("ScheduleShow", ctx, req)}
}

func (_c *MockAdminScheduleService_ScheduleShow_Call) Run(run func(ctx context.Context, req request.ScheduleShowRequest)) *MockAdminScheduleService_ScheduleShow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.ScheduleShowRequest
		if args[1] != nil {
			arg1 = args[1].(request.ScheduleShowRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminScheduleService_ScheduleShow_Call) Return(scheduleShowResponse *response.ScheduleShowResponse, err error) *MockAdminScheduleService_ScheduleShow_Call {
	_c.Call.Return(scheduleShowResponse, err)
	return _c
}

func (_c *MockAdminScheduleService_ScheduleShow_Call) RunAndReturn(run func(ctx context.Context, req request.ScheduleShowRequest) (*response.ScheduleShowResponse, error)) *MockAdminScheduleService_ScheduleShow_Call {
	_c.Call.Return(run)
	return _c
}
