// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSMSOTPServiceInterface creates a new instance of MockSMSOTPServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMSOTPServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMSOTPServiceInterface {
	mock := &MockSMSOTPServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSMSOTPServiceInterface is an autogenerated mock type for the SMSOTPServiceInterface type
type MockSMSOTPServiceInterface struct {
	mock.Mock
}

type MockSMSOTPServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSMSOTPServiceInterface) EXPECT() *MockSMSOTPServiceInterface_Expecter {
	return &MockSMSOTPServiceInterface_Expecter{mock: &_m.Mock}
}

// ListAllOTPs provides a mock function for the type MockSMSOTPServiceInterface
func (_mock *MockSMSOTPServiceInterface) ListAllOTPs(ctx context.Context) (*response.OTPListResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllOTPs")
	}

	var r0 *response.OTPListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*response.OTPListResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *response.OTPListResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OTPListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSMSOTPServiceInterface_ListAllOTPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllOTPs'
type MockSMSOTPServiceInterface_ListAllOTPs_Call struct {
	*mock.Call
}

// ListAllOTPs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSMSOTPServiceInterface_Expecter) ListAllOTPs(ctx interface{}) *MockSMSOTPServiceInterface_ListAllOTPs_Call {
	return &MockSMSOTPServiceInterface_ListAllOTPs_Call{Call: _e.mock.On("ListAllOTPs", ctx)}
}

func (_c *MockSMSOTPServiceInterface_ListAllOTPs_Call) Run(run func(ctx context.Context)) *MockSMSOTPServiceInterface_ListAllOTPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSMSOTPServiceInterface_ListAllOTPs_Call) Return(oTPListResponse *response.OTPListResponse, err error) *MockSMSOTPServiceInterface_ListAllOTPs_Call {
	_c.Call.Return(oTPListResponse, err)
	return _c
}

func (_c *MockSMSOTPServiceInterface_ListAllOTPs_Call) RunAndReturn(run func(ctx context.Context) (*response.OTPListResponse, error)) *MockSMSOTPServiceInterface_ListAllOTPs_Call {
	_c.Call.Return(run)
	return _c
}

// RequestOTP provides a mock function for the type MockSMSOTPServiceInterface
func (_mock *MockSMSOTPServiceInterface) RequestOTP(ctx context.Context, phoneNumber string, ip string) (*response.OTPSendResponse, error) {
	ret := _mock.Called(ctx, phoneNumber, ip)

	if len(ret) == 0 {
		panic("no return value specified for RequestOTP")
	}

	var r0 *response.OTPSendResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*response.OTPSendResponse, error)); ok {
		return returnFunc(ctx, phoneNumber, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *response.OTPSendResponse); ok {
		r0 = returnFunc(ctx, phoneNumber, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OTPSendResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, phoneNumber, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSMSOTPServiceInterface_RequestOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestOTP'
type MockSMSOTPServiceInterface_RequestOTP_Call struct {
	*mock.Call
}

// RequestOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
//   - ip string
func (_e *MockSMSOTPServiceInterface_Expecter) RequestOTP(ctx interface{}, phoneNumber interface{}, ip interface{}) *MockSMSOTPServiceInterface_RequestOTP_Call {
	return &MockSMSOTPServiceInterface_RequestOTP_Call{Call: _e.mock.On("RequestOTP", ctx, phoneNumber, ip)}
}

func (_c *MockSMSOTPServiceInterface_RequestOTP_Call) Run(run func(ctx context.Context, phoneNumber string, ip string)) *MockSMSOTPServiceInterface_RequestOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSMSOTPServiceInterface_RequestOTP_Call) Return(oTPSendResponse *response.OTPSendResponse, err error) *MockSMSOTPServiceInterface_RequestOTP_Call {
	_c.Call.Return(oTPSendResponse, err)
	return _c
}

func (_c *MockSMSOTPServiceInterface_RequestOTP_Call) RunAndReturn(run func(ctx context.Context, phoneNumber string, ip string) (*response.OTPSendResponse, error)) *MockSMSOTPServiceInterface_RequestOTP_Call {
	_c.Call.Return(run)
	return _c
}

// ResendOTP provides a mock function for the type MockSMSOTPServiceInterface
func (_mock *MockSMSOTPServiceInterface) ResendOTP(ctx context.Context, phoneNumber string, ip string) (*response.OTPSendResponse, error) {
	ret := _mock.Called(ctx, phoneNumber, ip)

	if len(ret) == 0 {
		panic("no return value specified for ResendOTP")
	}

	var r0 *response.OTPSendResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*response.OTPSendResponse, error)); ok {
		return returnFunc(ctx, phoneNumber, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *response.OTPSendResponse); ok {
		r0 = returnFunc(ctx, phoneNumber, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OTPSendResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, phoneNumber, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSMSOTPServiceInterface_ResendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendOTP'
type MockSMSOTPServiceInterface_ResendOTP_Call struct {
	*mock.Call
}

// ResendOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
//   - ip string
func (_e *MockSMSOTPServiceInterface_Expecter) ResendOTP(ctx interface{}, phoneNumber interface{}, ip interface{}) *MockSMSOTPServiceInterface_ResendOTP_Call {
	return &MockSMSOTPServiceInterface_ResendOTP_Call{Call: _e.mock.On("ResendOTP", ctx, phoneNumber, ip)}
}

func (_c *MockSMSOTPServiceInterface_ResendOTP_Call) Run(run func(ctx context.Context, phoneNumber string, ip string)) *MockSMSOTPServiceInterface_ResendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSMSOTPServiceInterface_ResendOTP_Call) Return(oTPSendResponse *response.OTPSendResponse, err error) *MockSMSOTPServiceInterface_ResendOTP_Call {
	_c.Call.Return(oTPSendResponse, err)
	return _c
}

func (_c *MockSMSOTPServiceInterface_ResendOTP_Call) RunAndReturn(run func(ctx context.Context, phoneNumber string, ip string) (*response.OTPSendResponse, error)) *MockSMSOTPServiceInterface_ResendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function for the type MockSMSOTPServiceInterface
func (_mock *MockSMSOTPServiceInterface) VerifyOTP(ctx context.Context, phoneNumber string, code string) (*response.OTPVerifyResponse, error) {
	ret := _mock.Called(ctx, phoneNumber, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 *response.OTPVerifyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*response.OTPVerifyResponse, error)); ok {
		return returnFunc(ctx, phoneNumber, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *response.OTPVerifyResponse); ok {
		r0 = returnFunc(ctx, phoneNumber, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OTPVerifyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, phoneNumber, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSMSOTPServiceInterface_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockSMSOTPServiceInterface_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
//   - code string
func (_e *MockSMSOTPServiceInterface_Expecter) VerifyOTP(ctx interface{}, phoneNumber interface{}, code interface{}) *MockSMSOTPServiceInterface_VerifyOTP_Call {
	return &MockSMSOTPServiceInterface_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, phoneNumber, code)}
}

func (_c *MockSMSOTPServiceInterface_VerifyOTP_Call) Run(run func(ctx context.Context, phoneNumber string, code string)) *MockSMSOTPServiceInterface_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSMSOTPServiceInterface_VerifyOTP_Call) Return(oTPVerifyResponse *response.OTPVerifyResponse, err error) *MockSMSOTPServiceInterface_VerifyOTP_Call {
	_c.Call.Return(oTPVerifyResponse, err)
	return _c
}

func (_c *MockSMSOTPServiceInterface_VerifyOTP_Call) RunAndReturn(run func(ctx context.Context, phoneNumber string, code string) (*response.OTPVerifyResponse, error)) *MockSMSOTPServiceInterface_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}
