// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/request"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerInterface creates a new instance of MockCustomerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerInterface {
	mock := &MockCustomerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerInterface is an autogenerated mock type for the CustomerInterface type
type MockCustomerInterface struct {
	mock.Mock
}

type MockCustomerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerInterface) EXPECT() *MockCustomerInterface_Expecter {
	return &MockCustomerInterface_Expecter{mock: &_m.Mock}
}

// ForgotPassword provides a mock function for the type MockCustomerInterface
func (_mock *MockCustomerInterface) ForgotPassword(ctx context.Context, email string) (string, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerInterface_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MockCustomerInterface_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockCustomerInterface_Expecter) ForgotPassword(ctx interface{}, email interface{}) *MockCustomerInterface_ForgotPassword_Call {
	return &MockCustomerInterface_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, email)}
}

func (_c *MockCustomerInterface_ForgotPassword_Call) Run(run func(ctx context.Context, email string)) *MockCustomerInterface_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerInterface_ForgotPassword_Call) Return(s string, err error) *MockCustomerInterface_ForgotPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCustomerInterface_ForgotPassword_Call) RunAndReturn(run func(ctx context.Context, email string) (string, error)) *MockCustomerInterface_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type MockCustomerInterface
func (_mock *MockCustomerInterface) GetProfile(ctx context.Context, userID uint) (*response.CustomerProfileResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *response.CustomerProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*response.CustomerProfileResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *response.CustomerProfileResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CustomerProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerInterface_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockCustomerInterface_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockCustomerInterface_Expecter) GetProfile(ctx interface{}, userID interface{}) *MockCustomerInterface_GetProfile_Call {
	return &MockCustomerInterface_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockCustomerInterface_GetProfile_Call) Run(run func(ctx context.Context, userID uint)) *MockCustomerInterface_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerInterface_GetProfile_Call) Return(customerProfileResponse *response.CustomerProfileResponse, err error) *MockCustomerInterface_GetProfile_Call {
	_c.Call.Return(customerProfileResponse, err)
	return _c
}

func (_c *MockCustomerInterface_GetProfile_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*response.CustomerProfileResponse, error)) *MockCustomerInterface_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockCustomerInterface
func (_mock *MockCustomerInterface) Login(context1 context.Context, customerLoginRequest request.CustomerLoginRequest) (*response.LoginResponse, error) {
	ret := _mock.Called(context1, customerLoginRequest)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *response.LoginResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CustomerLoginRequest) (*response.LoginResponse, error)); ok {
		return returnFunc(context1, customerLoginRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CustomerLoginRequest) *response.LoginResponse); ok {
		r0 = returnFunc(context1, customerLoginRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.CustomerLoginRequest) error); ok {
		r1 = returnFunc(context1, customerLoginRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerInterface_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockCustomerInterface_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - context1 context.Context
//   - customerLoginRequest request.CustomerLoginRequest
func (_e *MockCustomerInterface_Expecter) Login(context1 interface{}, customerLoginRequest interface{}) *MockCustomerInterface_Login_Call {
	return &MockCustomerInterface_Login_Call{Call: _e.mock.On("Login", context1, customerLoginRequest)}
}

func (_c *MockCustomerInterface_Login_Call) Run(run func(context1 context.Context, customerLoginRequest request.CustomerLoginRequest)) *MockCustomerInterface_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.CustomerLoginRequest
		if args[1] != nil {
			arg1 = args[1].(request.CustomerLoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerInterface_Login_Call) Return(loginResponse *response.LoginResponse, err error) *MockCustomerInterface_Login_Call {
	_c.Call.Return(loginResponse, err)
	return _c
}

func (_c *MockCustomerInterface_Login_Call) RunAndReturn(run func(context1 context.Context, customerLoginRequest request.CustomerLoginRequest) (*response.LoginResponse, error)) *MockCustomerInterface_Login_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockCustomerInterface
func (_mock *MockCustomerInterface) ResetPassword(ctx context.Context, token string, password string) error {
	ret := _mock.Called(ctx, token, password)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerInterface_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockCustomerInterface_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - password string
func (_e *MockCustomerInterface_Expecter) ResetPassword(ctx interface{}, token interface{}, password interface{}) *MockCustomerInterface_ResetPassword_Call {
	return &MockCustomerInterface_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, token, password)}
}

func (_c *MockCustomerInterface_ResetPassword_Call) Run(run func(ctx context.Context, token string, password string)) *MockCustomerInterface_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomerInterface_ResetPassword_Call) Return(err error) *MockCustomerInterface_ResetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerInterface_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, token string, password string) error) *MockCustomerInterface_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Signup provides a mock function for the type MockCustomerInterface
func (_mock *MockCustomerInterface) Signup(context1 context.Context, customerSignupRequest request.CustomerSignupRequest) (*response.LoginResponse, error) {
	ret := _mock.Called(context1, customerSignupRequest)

	if len(ret) == 0 {
		panic("no return value specified for Signup")
	}

	var r0 *response.LoginResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CustomerSignupRequest) (*response.LoginResponse, error)); ok {
		return returnFunc(context1, customerSignupRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CustomerSignupRequest) *response.LoginResponse); ok {
		r0 = returnFunc(context1, customerSignupRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.CustomerSignupRequest) error); ok {
		r1 = returnFunc(context1, customerSignupRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerInterface_Signup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signup'
type MockCustomerInterface_Signup_Call struct {
	*mock.Call
}

// Signup is a helper method to define mock.On call
//   - context1 context.Context
//   - customerSignupRequest request.CustomerSignupRequest
func (_e *MockCustomerInterface_Expecter) Signup(context1 interface{}, customerSignupRequest interface{}) *MockCustomerInterface_Signup_Call {
	return &MockCustomerInterface_Signup_Call{Call: _e.mock.On("Signup", context1, customerSignupRequest)}
}

func (_c *MockCustomerInterface_Signup_Call) Run(run func(context1 context.Context, customerSignupRequest request.CustomerSignupRequest)) *MockCustomerInterface_Signup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.CustomerSignupRequest
		if args[1] != nil {
			arg1 = args[1].(request.CustomerSignupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerInterface_Signup_Call) Return(loginResponse *response.LoginResponse, err error) *MockCustomerInterface_Signup_Call {
	_c.Call.Return(loginResponse, err)
	return _c
}

func (_c *MockCustomerInterface_Signup_Call) RunAndReturn(run func(context1 context.Context, customerSignupRequest request.CustomerSignupRequest) (*response.LoginResponse, error)) *MockCustomerInterface_Signup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockCustomerInterface
func (_mock *MockCustomerInterface) UpdateProfile(ctx context.Context, userID uint, req request.CustomerUpdateProfileRequest) (*response.UpdateProfileResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *response.UpdateProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, request.CustomerUpdateProfileRequest) (*response.UpdateProfileResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, request.CustomerUpdateProfileRequest) *response.UpdateProfileResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UpdateProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, request.CustomerUpdateProfileRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerInterface_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockCustomerInterface_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - req request.CustomerUpdateProfileRequest
func (_e *MockCustomerInterface_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MockCustomerInterface_UpdateProfile_Call {
	return &MockCustomerInterface_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MockCustomerInterface_UpdateProfile_Call) Run(run func(ctx context.Context, userID uint, req request.CustomerUpdateProfileRequest)) *MockCustomerInterface_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 request.CustomerUpdateProfileRequest
		if args[2] != nil {
			arg2 = args[2].(request.CustomerUpdateProfileRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomerInterface_UpdateProfile_Call) Return(updateProfileResponse *response.UpdateProfileResponse, err error) *MockCustomerInterface_UpdateProfile_Call {
	_c.Call.Return(updateProfileResponse, err)
	return _c
}

func (_c *MockCustomerInterface_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, userID uint, req request.CustomerUpdateProfileRequest) (*response.UpdateProfileResponse, error)) *MockCustomerInterface_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyResetToken provides a mock function for the type MockCustomerInterface
func (_mock *MockCustomerInterface) VerifyResetToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyResetToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerInterface_VerifyResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyResetToken'
type MockCustomerInterface_VerifyResetToken_Call struct {
	*mock.Call
}

// VerifyResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockCustomerInterface_Expecter) VerifyResetToken(ctx interface{}, token interface{}) *MockCustomerInterface_VerifyResetToken_Call {
	return &MockCustomerInterface_VerifyResetToken_Call{Call: _e.mock.On("VerifyResetToken", ctx, token)}
}

func (_c *MockCustomerInterface_VerifyResetToken_Call) Run(run func(ctx context.Context, token string)) *MockCustomerInterface_VerifyResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerInterface_VerifyResetToken_Call) Return(err error) *MockCustomerInterface_VerifyResetToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerInterface_VerifyResetToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockCustomerInterface_VerifyResetToken_Call {
	_c.Call.Return(run)
	return _c
}
