// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/response"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShowService creates a new instance of MockShowService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShowService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShowService {
	mock := &MockShowService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShowService is an autogenerated mock type for the ShowService type
type MockShowService struct {
	mock.Mock
}

type MockShowService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShowService) EXPECT() *MockShowService_Expecter {
	return &MockShowService_Expecter{mock: &_m.Mock}
}

// GetMovieAvailableDates provides a mock function for the type MockShowService
func (_mock *MockShowService) GetMovieAvailableDates(context1 context.Context, s string) ([]string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieAvailableDates")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowService_GetMovieAvailableDates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieAvailableDates'
type MockShowService_GetMovieAvailableDates_Call struct {
	*mock.Call
}

// GetMovieAvailableDates is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockShowService_Expecter) GetMovieAvailableDates(context1 interface{}, s interface{}) *MockShowService_GetMovieAvailableDates_Call {
	return &MockShowService_GetMovieAvailableDates_Call{Call: _e.mock.On("GetMovieAvailableDates", context1, s)}
}

func (_c *MockShowService_GetMovieAvailableDates_Call) Run(run func(context1 context.Context, s string)) *MockShowService_GetMovieAvailableDates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowService_GetMovieAvailableDates_Call) Return(strings []string, err error) *MockShowService_GetMovieAvailableDates_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockShowService_GetMovieAvailableDates_Call) RunAndReturn(run func(context1 context.Context, s string) ([]string, error)) *MockShowService_GetMovieAvailableDates_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieById provides a mock function for the type MockShowService
func (_mock *MockShowService) GetMovieById(context1 context.Context, s string) (*model.Movie, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieById")
	}

	var r0 *model.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Movie, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Movie); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowService_GetMovieById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieById'
type MockShowService_GetMovieById_Call struct {
	*mock.Call
}

// GetMovieById is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockShowService_Expecter) GetMovieById(context1 interface{}, s interface{}) *MockShowService_GetMovieById_Call {
	return &MockShowService_GetMovieById_Call{Call: _e.mock.On("GetMovieById", context1, s)}
}

func (_c *MockShowService_GetMovieById_Call) Run(run func(context1 context.Context, s string)) *MockShowService_GetMovieById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowService_GetMovieById_Call) Return(movie *model.Movie, err error) *MockShowService_GetMovieById_Call {
	_c.Call.Return(movie, err)
	return _c
}

func (_c *MockShowService_GetMovieById_Call) RunAndReturn(run func(context1 context.Context, s string) (*model.Movie, error)) *MockShowService_GetMovieById_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieShowtimes provides a mock function for the type MockShowService
func (_mock *MockShowService) GetMovieShowtimes(context1 context.Context, s string, s1 string) ([]response.ShowtimeResponse, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieShowtimes")
	}

	var r0 []response.ShowtimeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]response.ShowtimeResponse, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []response.ShowtimeResponse); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.ShowtimeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowService_GetMovieShowtimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieShowtimes'
type MockShowService_GetMovieShowtimes_Call struct {
	*mock.Call
}

// GetMovieShowtimes is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockShowService_Expecter) GetMovieShowtimes(context1 interface{}, s interface{}, s1 interface{}) *MockShowService_GetMovieShowtimes_Call {
	return &MockShowService_GetMovieShowtimes_Call{Call: _e.mock.On("GetMovieShowtimes", context1, s, s1)}
}

func (_c *MockShowService_GetMovieShowtimes_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockShowService_GetMovieShowtimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShowService_GetMovieShowtimes_Call) Return(showtimeResponses []response.ShowtimeResponse, err error) *MockShowService_GetMovieShowtimes_Call {
	_c.Call.Return(showtimeResponses, err)
	return _c
}

func (_c *MockShowService_GetMovieShowtimes_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) ([]response.ShowtimeResponse, error)) *MockShowService_GetMovieShowtimes_Call {
	_c.Call.Return(run)
	return _c
}

// GetScheduledMovies provides a mock function for the type MockShowService
func (_mock *MockShowService) GetScheduledMovies(context1 context.Context) ([]model.Movie, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetScheduledMovies")
	}

	var r0 []model.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Movie, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Movie); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowService_GetScheduledMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduledMovies'
type MockShowService_GetScheduledMovies_Call struct {
	*mock.Call
}

// GetScheduledMovies is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockShowService_Expecter) GetScheduledMovies(context1 interface{}) *MockShowService_GetScheduledMovies_Call {
	return &MockShowService_GetScheduledMovies_Call{Call: _e.mock.On("GetScheduledMovies", context1)}
}

func (_c *MockShowService_GetScheduledMovies_Call) Run(run func(context1 context.Context)) *MockShowService_GetScheduledMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShowService_GetScheduledMovies_Call) Return(movies []model.Movie, err error) *MockShowService_GetScheduledMovies_Call {
	_c.Call.Return(movies, err)
	return _c
}

func (_c *MockShowService_GetScheduledMovies_Call) RunAndReturn(run func(context1 context.Context) ([]model.Movie, error)) *MockShowService_GetScheduledMovies_Call {
	_c.Call.Return(run)
	return _c
}

// GetShows provides a mock function for the type MockShowService
func (_mock *MockShowService) GetShows(context1 context.Context, s string) ([]model.Show, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetShows")
	}

	var r0 []model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Show, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Show); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowService_GetShows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShows'
type MockShowService_GetShows_Call struct {
	*mock.Call
}

// GetShows is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockShowService_Expecter) GetShows(context1 interface{}, s interface{}) *MockShowService_GetShows_Call {
	return &MockShowService_GetShows_Call{Call: _e.mock.On("GetShows", context1, s)}
}

func (_c *MockShowService_GetShows_Call) Run(run func(context1 context.Context, s string)) *MockShowService_GetShows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowService_GetShows_Call) Return(shows []model.Show, err error) *MockShowService_GetShows_Call {
	_c.Call.Return(shows, err)
	return _c
}

func (_c *MockShowService_GetShows_Call) RunAndReturn(run func(context1 context.Context, s string) ([]model.Show, error)) *MockShowService_GetShows_Call {
	_c.Call.Return(run)
	return _c
}
