// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/request"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingViewService creates a new instance of MockBookingViewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingViewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingViewService {
	mock := &MockBookingViewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingViewService is an autogenerated mock type for the BookingViewService type
type MockBookingViewService struct {
	mock.Mock
}

type MockBookingViewService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingViewService) EXPECT() *MockBookingViewService_Expecter {
	return &MockBookingViewService_Expecter{mock: &_m.Mock}
}

// GetAllBookings provides a mock function for the type MockBookingViewService
func (_mock *MockBookingViewService) GetAllBookings(ctx context.Context, filter request.AdminBookingViewRequest) (*response.AdminBookingViewResponse, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBookings")
	}

	var r0 *response.AdminBookingViewResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.AdminBookingViewRequest) (*response.AdminBookingViewResponse, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.AdminBookingViewRequest) *response.AdminBookingViewResponse); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AdminBookingViewResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.AdminBookingViewRequest) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingViewService_GetAllBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBookings'
type MockBookingViewService_GetAllBookings_Call struct {
	*mock.Call
}

// GetAllBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - filter request.AdminBookingViewRequest
func (_e *MockBookingViewService_Expecter) GetAllBookings(ctx interface{}, filter interface{}) *MockBookingViewService_GetAllBookings_Call {
	return &MockBookingViewService_GetAllBookings_Call{Call: _e.mock.On("GetAllBookings", ctx, filter)}
}

func (_c *MockBookingViewService_GetAllBookings_Call) Run(run func(ctx context.Context, filter request.AdminBookingViewRequest)) *MockBookingViewService_GetAllBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.AdminBookingViewRequest
		if args[1] != nil {
			arg1 = args[1].(request.AdminBookingViewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingViewService_GetAllBookings_Call) Return(adminBookingViewResponse *response.AdminBookingViewResponse, err error) *MockBookingViewService_GetAllBookings_Call {
	_c.Call.Return(adminBookingViewResponse, err)
	return _c
}

func (_c *MockBookingViewService_GetAllBookings_Call) RunAndReturn(run func(ctx context.Context, filter request.AdminBookingViewRequest) (*response.AdminBookingViewResponse, error)) *MockBookingViewService_GetAllBookings_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBookingsCustomer provides a mock function for the type MockBookingViewService
func (_mock *MockBookingViewService) GetAllBookingsCustomer(ctx context.Context, filter request.CustomerBookingViewRequest) (*response.AdminBookingViewResponse, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBookingsCustomer")
	}

	var r0 *response.AdminBookingViewResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CustomerBookingViewRequest) (*response.AdminBookingViewResponse, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CustomerBookingViewRequest) *response.AdminBookingViewResponse); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AdminBookingViewResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.CustomerBookingViewRequest) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingViewService_GetAllBookingsCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBookingsCustomer'
type MockBookingViewService_GetAllBookingsCustomer_Call struct {
	*mock.Call
}

// GetAllBookingsCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - filter request.CustomerBookingViewRequest
func (_e *MockBookingViewService_Expecter) GetAllBookingsCustomer(ctx interface{}, filter interface{}) *MockBookingViewService_GetAllBookingsCustomer_Call {
	return &MockBookingViewService_GetAllBookingsCustomer_Call{Call: _e.mock.On("GetAllBookingsCustomer", ctx, filter)}
}

func (_c *MockBookingViewService_GetAllBookingsCustomer_Call) Run(run func(ctx context.Context, filter request.CustomerBookingViewRequest)) *MockBookingViewService_GetAllBookingsCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.CustomerBookingViewRequest
		if args[1] != nil {
			arg1 = args[1].(request.CustomerBookingViewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingViewService_GetAllBookingsCustomer_Call) Return(adminBookingViewResponse *response.AdminBookingViewResponse, err error) *MockBookingViewService_GetAllBookingsCustomer_Call {
	_c.Call.Return(adminBookingViewResponse, err)
	return _c
}

func (_c *MockBookingViewService_GetAllBookingsCustomer_Call) RunAndReturn(run func(ctx context.Context, filter request.CustomerBookingViewRequest) (*response.AdminBookingViewResponse, error)) *MockBookingViewService_GetAllBookingsCustomer_Call {
	_c.Call.Return(run)
	return _c
}
