// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileImageService creates a new instance of MockProfileImageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileImageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileImageService {
	mock := &MockProfileImageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileImageService is an autogenerated mock type for the ProfileImageService type
type MockProfileImageService struct {
	mock.Mock
}

type MockProfileImageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileImageService) EXPECT() *MockProfileImageService_Expecter {
	return &MockProfileImageService_Expecter{mock: &_m.Mock}
}

// GetProfileImage provides a mock function for the type MockProfileImageService
func (_mock *MockProfileImageService) GetProfileImage(ctx context.Context, userID uint) (*response.AvatarResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileImage")
	}

	var r0 *response.AvatarResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*response.AvatarResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *response.AvatarResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AvatarResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileImageService_GetProfileImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileImage'
type MockProfileImageService_GetProfileImage_Call struct {
	*mock.Call
}

// GetProfileImage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockProfileImageService_Expecter) GetProfileImage(ctx interface{}, userID interface{}) *MockProfileImageService_GetProfileImage_Call {
	return &MockProfileImageService_GetProfileImage_Call{Call: _e.mock.On("GetProfileImage", ctx, userID)}
}

func (_c *MockProfileImageService_GetProfileImage_Call) Run(run func(ctx context.Context, userID uint)) *MockProfileImageService_GetProfileImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileImageService_GetProfileImage_Call) Return(avatarResponse *response.AvatarResponse, err error) *MockProfileImageService_GetProfileImage_Call {
	_c.Call.Return(avatarResponse, err)
	return _c
}

func (_c *MockProfileImageService_GetProfileImage_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*response.AvatarResponse, error)) *MockProfileImageService_GetProfileImage_Call {
	_c.Call.Return(run)
	return _c
}

// UploadProfileImage provides a mock function for the type MockProfileImageService
func (_mock *MockProfileImageService) UploadProfileImage(ctx context.Context, userID uint, imageData []byte, contentType string) (*response.AvatarResponse, error) {
	ret := _mock.Called(ctx, userID, imageData, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadProfileImage")
	}

	var r0 *response.AvatarResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []byte, string) (*response.AvatarResponse, error)); ok {
		return returnFunc(ctx, userID, imageData, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []byte, string) *response.AvatarResponse); ok {
		r0 = returnFunc(ctx, userID, imageData, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AvatarResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []byte, string) error); ok {
		r1 = returnFunc(ctx, userID, imageData, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileImageService_UploadProfileImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadProfileImage'
type MockProfileImageService_UploadProfileImage_Call struct {
	*mock.Call
}

// UploadProfileImage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - imageData []byte
//   - contentType string
func (_e *MockProfileImageService_Expecter) UploadProfileImage(ctx interface{}, userID interface{}, imageData interface{}, contentType interface{}) *MockProfileImageService_UploadProfileImage_Call {
	return &MockProfileImageService_UploadProfileImage_Call{Call: _e.mock.On("UploadProfileImage", ctx, userID, imageData, contentType)}
}

func (_c *MockProfileImageService_UploadProfileImage_Call) Run(run func(ctx context.Context, userID uint, imageData []byte, contentType string)) *MockProfileImageService_UploadProfileImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProfileImageService_UploadProfileImage_Call) Return(avatarResponse *response.AvatarResponse, err error) *MockProfileImageService_UploadProfileImage_Call {
	_c.Call.Return(avatarResponse, err)
	return _c
}

func (_c *MockProfileImageService_UploadProfileImage_Call) RunAndReturn(run func(ctx context.Context, userID uint, imageData []byte, contentType string) (*response.AvatarResponse, error)) *MockProfileImageService_UploadProfileImage_Call {
	_c.Call.Return(run)
	return _c
}
