// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/response"
	"skyfox/bookings/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRevenueService creates a new instance of MockRevenueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRevenueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRevenueService {
	mock := &MockRevenueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRevenueService is an autogenerated mock type for the RevenueService type
type MockRevenueService struct {
	mock.Mock
}

type MockRevenueService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRevenueService) EXPECT() *MockRevenueService_Expecter {
	return &MockRevenueService_Expecter{mock: &_m.Mock}
}

// RevenueBy provides a mock function for the type MockRevenueService
func (_mock *MockRevenueService) RevenueBy(ctx context.Context, revenueQuery *repository.RevenueQuery) (*response.RevenueResponse, error) {
	ret := _mock.Called(ctx, revenueQuery)

	if len(ret) == 0 {
		panic("no return value specified for RevenueBy")
	}

	var r0 *response.RevenueResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.RevenueQuery) (*response.RevenueResponse, error)); ok {
		return returnFunc(ctx, revenueQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.RevenueQuery) *response.RevenueResponse); ok {
		r0 = returnFunc(ctx, revenueQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.RevenueResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repository.RevenueQuery) error); ok {
		r1 = returnFunc(ctx, revenueQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRevenueService_RevenueBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevenueBy'
type MockRevenueService_RevenueBy_Call struct {
	*mock.Call
}

// RevenueBy is a helper method to define mock.On call
//   - ctx context.Context
//   - revenueQuery *repository.RevenueQuery
func (_e *MockRevenueService_Expecter) RevenueBy(ctx interface{}, revenueQuery interface{}) *MockRevenueService_RevenueBy_Call {
	return &MockRevenueService_RevenueBy_Call{Call: _e.mock.On("RevenueBy", ctx, revenueQuery)}
}

func (_c *MockRevenueService_RevenueBy_Call) Run(run func(ctx context.Context, revenueQuery *repository.RevenueQuery)) *MockRevenueService_RevenueBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.RevenueQuery
		if args[1] != nil {
			arg1 = args[1].(*repository.RevenueQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRevenueService_RevenueBy_Call) Return(revenueResponse *response.RevenueResponse, err error) *MockRevenueService_RevenueBy_Call {
	_c.Call.Return(revenueResponse, err)
	return _c
}

func (_c *MockRevenueService_RevenueBy_Call) RunAndReturn(run func(ctx context.Context, revenueQuery *repository.RevenueQuery) (*response.RevenueResponse, error)) *MockRevenueService_RevenueBy_Call {
	_c.Call.Return(run)
	return _c
}
