// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"
	"skyfox/common/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMovieService creates a new instance of MockMovieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMovieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMovieService {
	mock := &MockMovieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMovieService is an autogenerated mock type for the MovieService type
type MockMovieService struct {
	mock.Mock
}

type MockMovieService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMovieService) EXPECT() *MockMovieService_Expecter {
	return &MockMovieService_Expecter{mock: &_m.Mock}
}

// GetAllMovies provides a mock function for the type MockMovieService
func (_mock *MockMovieService) GetAllMovies(ctx context.Context) ([]response.MovieResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMovies")
	}

	var r0 []response.MovieResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]response.MovieResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []response.MovieResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.MovieResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMovieService_GetAllMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMovies'
type MockMovieService_GetAllMovies_Call struct {
	*mock.Call
}

// GetAllMovies is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMovieService_Expecter) GetAllMovies(ctx interface{}) *MockMovieService_GetAllMovies_Call {
	return &MockMovieService_GetAllMovies_Call{Call: _e.mock.On("GetAllMovies", ctx)}
}

func (_c *MockMovieService_GetAllMovies_Call) Run(run func(ctx context.Context)) *MockMovieService_GetAllMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMovieService_GetAllMovies_Call) Return(movieResponses []response.MovieResponse, err error) *MockMovieService_GetAllMovies_Call {
	_c.Call.Return(movieResponses, err)
	return _c
}

func (_c *MockMovieService_GetAllMovies_Call) RunAndReturn(run func(ctx context.Context) ([]response.MovieResponse, error)) *MockMovieService_GetAllMovies_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieByID provides a mock function for the type MockMovieService
func (_mock *MockMovieService) GetMovieByID(ctx context.Context, movieID string) (*model.Movie, error) {
	ret := _mock.Called(ctx, movieID)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieByID")
	}

	var r0 *model.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Movie, error)); ok {
		return returnFunc(ctx, movieID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Movie); ok {
		r0 = returnFunc(ctx, movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, movieID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMovieService_GetMovieByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieByID'
type MockMovieService_GetMovieByID_Call struct {
	*mock.Call
}

// GetMovieByID is a helper method to define mock.On call
//   - ctx context.Context
//   - movieID string
func (_e *MockMovieService_Expecter) GetMovieByID(ctx interface{}, movieID interface{}) *MockMovieService_GetMovieByID_Call {
	return &MockMovieService_GetMovieByID_Call{Call: _e.mock.On("GetMovieByID", ctx, movieID)}
}

func (_c *MockMovieService_GetMovieByID_Call) Run(run func(ctx context.Context, movieID string)) *MockMovieService_GetMovieByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMovieService_GetMovieByID_Call) Return(movie *model.Movie, err error) *MockMovieService_GetMovieByID_Call {
	_c.Call.Return(movie, err)
	return _c
}

func (_c *MockMovieService_GetMovieByID_Call) RunAndReturn(run func(ctx context.Context, movieID string) (*model.Movie, error)) *MockMovieService_GetMovieByID_Call {
	_c.Call.Return(run)
	return _c
}
