// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// newMockavatarAssigner creates a new instance of mockavatarAssigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockavatarAssigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockavatarAssigner {
	mock := &mockavatarAssigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockavatarAssigner is an autogenerated mock type for the avatarAssigner type
type mockavatarAssigner struct {
	mock.Mock
}

type mockavatarAssigner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockavatarAssigner) EXPECT() *mockavatarAssigner_Expecter {
	return &mockavatarAssigner_Expecter{mock: &_m.Mock}
}

// AssignRandomAvatar provides a mock function for the type mockavatarAssigner
func (_mock *mockavatarAssigner) AssignRandomAvatar(ctx context.Context, userID uint, gender string) (*response.AvatarResponse, error) {
	ret := _mock.Called(ctx, userID, gender)

	if len(ret) == 0 {
		panic("no return value specified for AssignRandomAvatar")
	}

	var r0 *response.AvatarResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (*response.AvatarResponse, error)); ok {
		return returnFunc(ctx, userID, gender)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) *response.AvatarResponse); ok {
		r0 = returnFunc(ctx, userID, gender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AvatarResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, gender)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockavatarAssigner_AssignRandomAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRandomAvatar'
type mockavatarAssigner_AssignRandomAvatar_Call struct {
	*mock.Call
}

// AssignRandomAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - gender string
func (_e *mockavatarAssigner_Expecter) AssignRandomAvatar(ctx interface{}, userID interface{}, gender interface{}) *mockavatarAssigner_AssignRandomAvatar_Call {
	return &mockavatarAssigner_AssignRandomAvatar_Call{Call: _e.mock.On("AssignRandomAvatar", ctx, userID, gender)}
}

func (_c *mockavatarAssigner_AssignRandomAvatar_Call) Run(run func(ctx context.Context, userID uint, gender string)) *mockavatarAssigner_AssignRandomAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockavatarAssigner_AssignRandomAvatar_Call) Return(avatarResponse *response.AvatarResponse, err error) *mockavatarAssigner_AssignRandomAvatar_Call {
	_c.Call.Return(avatarResponse, err)
	return _c
}

func (_c *mockavatarAssigner_AssignRandomAvatar_Call) RunAndReturn(run func(ctx context.Context, userID uint, gender string) (*response.AvatarResponse, error)) *mockavatarAssigner_AssignRandomAvatar_Call {
	_c.Call.Return(run)
	return _c
}
