// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Create(context1 context.Context, customer *model.Customer) error {
	ret := _mock.Called(context1, customer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Customer) error); ok {
		r0 = returnFunc(context1, customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCustomerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - customer *model.Customer
func (_e *MockCustomerRepository_Expecter) Create(context1 interface{}, customer interface{}) *MockCustomerRepository_Create_Call {
	return &MockCustomerRepository_Create_Call{Call: _e.mock.On("Create", context1, customer)}
}

func (_c *MockCustomerRepository_Create_Call) Run(run func(context1 context.Context, customer *model.Customer)) *MockCustomerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Customer
		if args[1] != nil {
			arg1 = args[1].(*model.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Create_Call) Return(err error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Create_Call) RunAndReturn(run func(context1 context.Context, customer *model.Customer) error) *MockCustomerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) FindByEmail(ctx context.Context, email string) (*model.Customer, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Customer, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockCustomerRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockCustomerRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockCustomerRepository_FindByEmail_Call {
	return &MockCustomerRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockCustomerRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockCustomerRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_FindByEmail_Call) Return(customer *model.Customer, err error) *MockCustomerRepository_FindByEmail_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.Customer, error)) *MockCustomerRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) FindByID(ctx context.Context, userID uint) (*model.Customer, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*model.Customer, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *model.Customer); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCustomerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockCustomerRepository_Expecter) FindByID(ctx interface{}, userID interface{}) *MockCustomerRepository_FindByID_Call {
	return &MockCustomerRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID)}
}

func (_c *MockCustomerRepository_FindByID_Call) Run(run func(ctx context.Context, userID uint)) *MockCustomerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_FindByID_Call) Return(customer *model.Customer, err error) *MockCustomerRepository_FindByID_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*model.Customer, error)) *MockCustomerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByResetToken provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) FindByResetToken(ctx context.Context, token string) (*model.Customer, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByResetToken")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Customer, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_FindByResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByResetToken'
type MockCustomerRepository_FindByResetToken_Call struct {
	*mock.Call
}

// FindByResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockCustomerRepository_Expecter) FindByResetToken(ctx interface{}, token interface{}) *MockCustomerRepository_FindByResetToken_Call {
	return &MockCustomerRepository_FindByResetToken_Call{Call: _e.mock.On("FindByResetToken", ctx, token)}
}

func (_c *MockCustomerRepository_FindByResetToken_Call) Run(run func(ctx context.Context, token string)) *MockCustomerRepository_FindByResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_FindByResetToken_Call) Return(customer *model.Customer, err error) *MockCustomerRepository_FindByResetToken_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_FindByResetToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*model.Customer, error)) *MockCustomerRepository_FindByResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) FindByUsername(context1 context.Context, s string) (*model.Customer, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Customer, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockCustomerRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockCustomerRepository_Expecter) FindByUsername(context1 interface{}, s interface{}) *MockCustomerRepository_FindByUsername_Call {
	return &MockCustomerRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", context1, s)}
}

func (_c *MockCustomerRepository_FindByUsername_Call) Run(run func(context1 context.Context, s string)) *MockCustomerRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_FindByUsername_Call) Return(customer *model.Customer, err error) *MockCustomerRepository_FindByUsername_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_FindByUsername_Call) RunAndReturn(run func(context1 context.Context, s string) (*model.Customer, error)) *MockCustomerRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Update(ctx context.Context, customer *model.Customer) error {
	ret := _mock.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Customer) error); ok {
		r0 = returnFunc(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCustomerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - customer *model.Customer
func (_e *MockCustomerRepository_Expecter) Update(ctx interface{}, customer interface{}) *MockCustomerRepository_Update_Call {
	return &MockCustomerRepository_Update_Call{Call: _e.mock.On("Update", ctx, customer)}
}

func (_c *MockCustomerRepository_Update_Call) Run(run func(ctx context.Context, customer *model.Customer)) *MockCustomerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Customer
		if args[1] != nil {
			arg1 = args[1].(*model.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Update_Call) Return(err error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Update_Call) RunAndReturn(run func(ctx context.Context, customer *model.Customer) error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) UpdateProfile(ctx context.Context, customer *model.Customer) error {
	ret := _mock.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Customer) error); ok {
		r0 = returnFunc(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockCustomerRepository_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - customer *model.Customer
func (_e *MockCustomerRepository_Expecter) UpdateProfile(ctx interface{}, customer interface{}) *MockCustomerRepository_UpdateProfile_Call {
	return &MockCustomerRepository_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, customer)}
}

func (_c *MockCustomerRepository_UpdateProfile_Call) Run(run func(ctx context.Context, customer *model.Customer)) *MockCustomerRepository_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Customer
		if args[1] != nil {
			arg1 = args[1].(*model.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_UpdateProfile_Call) Return(err error) *MockCustomerRepository_UpdateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, customer *model.Customer) error) *MockCustomerRepository_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
