// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPhoneOTPChecker creates a new instance of MockPhoneOTPChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPhoneOTPChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPhoneOTPChecker {
	mock := &MockPhoneOTPChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPhoneOTPChecker is an autogenerated mock type for the PhoneOTPChecker type
type MockPhoneOTPChecker struct {
	mock.Mock
}

type MockPhoneOTPChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPhoneOTPChecker) EXPECT() *MockPhoneOTPChecker_Expecter {
	return &MockPhoneOTPChecker_Expecter{mock: &_m.Mock}
}

// IsRecipientVerified provides a mock function for the type MockPhoneOTPChecker
func (_mock *MockPhoneOTPChecker) IsRecipientVerified(ctx context.Context, recipient string, otpType string) (bool, error) {
	ret := _mock.Called(ctx, recipient, otpType)

	if len(ret) == 0 {
		panic("no return value specified for IsRecipientVerified")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, recipient, otpType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, recipient, otpType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, recipient, otpType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPhoneOTPChecker_IsRecipientVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRecipientVerified'
type MockPhoneOTPChecker_IsRecipientVerified_Call struct {
	*mock.Call
}

// IsRecipientVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - recipient string
//   - otpType string
func (_e *MockPhoneOTPChecker_Expecter) IsRecipientVerified(ctx interface{}, recipient interface{}, otpType interface{}) *MockPhoneOTPChecker_IsRecipientVerified_Call {
	return &MockPhoneOTPChecker_IsRecipientVerified_Call{Call: _e.mock.On("IsRecipientVerified", ctx, recipient, otpType)}
}

func (_c *MockPhoneOTPChecker_IsRecipientVerified_Call) Run(run func(ctx context.Context, recipient string, otpType string)) *MockPhoneOTPChecker_IsRecipientVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPhoneOTPChecker_IsRecipientVerified_Call) Return(b bool, err error) *MockPhoneOTPChecker_IsRecipientVerified_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPhoneOTPChecker_IsRecipientVerified_Call) RunAndReturn(run func(ctx context.Context, recipient string, otpType string) (bool, error)) *MockPhoneOTPChecker_IsRecipientVerified_Call {
	_c.Call.Return(run)
	return _c
}
