// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminScheduleRepository creates a new instance of MockAdminScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminScheduleRepository {
	mock := &MockAdminScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminScheduleRepository is an autogenerated mock type for the AdminScheduleRepository type
type MockAdminScheduleRepository struct {
	mock.Mock
}

type MockAdminScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminScheduleRepository) EXPECT() *MockAdminScheduleRepository_Expecter {
	return &MockAdminScheduleRepository_Expecter{mock: &_m.Mock}
}

// CreateScreen provides a mock function for the type MockAdminScheduleRepository
func (_mock *MockAdminScheduleRepository) CreateScreen(ctx context.Context, screen *model.Screen) error {
	ret := _mock.Called(ctx, screen)

	if len(ret) == 0 {
		panic("no return value specified for CreateScreen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Screen) error); ok {
		r0 = returnFunc(ctx, screen)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminScheduleRepository_CreateScreen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateScreen'
type MockAdminScheduleRepository_CreateScreen_Call struct {
	*mock.Call
}

// CreateScreen is a helper method to define mock.On call
//   - ctx context.Context
//   - screen *model.Screen
func (_e *MockAdminScheduleRepository_Expecter) CreateScreen(ctx interface{}, screen interface{}) *MockAdminScheduleRepository_CreateScreen_Call {
	return &MockAdminScheduleRepository_CreateScreen_Call{Call: _e.mock.On("CreateScreen", ctx, screen)}
}

func (_c *MockAdminScheduleRepository_CreateScreen_Call) Run(run func(ctx context.Context, screen *model.Screen)) *MockAdminScheduleRepository_CreateScreen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Screen
		if args[1] != nil {
			arg1 = args[1].(*model.Screen)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminScheduleRepository_CreateScreen_Call) Return(err error) *MockAdminScheduleRepository_CreateScreen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminScheduleRepository_CreateScreen_Call) RunAndReturn(run func(ctx context.Context, screen *model.Screen) error) *MockAdminScheduleRepository_CreateScreen_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShow provides a mock function for the type MockAdminScheduleRepository
func (_mock *MockAdminScheduleRepository) CreateShow(ctx context.Context, show *model.Show) error {
	ret := _mock.Called(ctx, show)

	if len(ret) == 0 {
		panic("no return value specified for CreateShow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Show) error); ok {
		r0 = returnFunc(ctx, show)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminScheduleRepository_CreateShow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShow'
type MockAdminScheduleRepository_CreateShow_Call struct {
	*mock.Call
}

// CreateShow is a helper method to define mock.On call
//   - ctx context.Context
//   - show *model.Show
func (_e *MockAdminScheduleRepository_Expecter) CreateShow(ctx interface{}, show interface{}) *MockAdminScheduleRepository_CreateShow_Call {
	return &MockAdminScheduleRepository_CreateShow_Call{Call: _e.mock.On("CreateShow", ctx, show)}
}

func (_c *MockAdminScheduleRepository_CreateShow_Call) Run(run func(ctx context.Context, show *model.Show)) *MockAdminScheduleRepository_CreateShow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Show
		if args[1] != nil {
			arg1 = args[1].(*model.Show)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminScheduleRepository_CreateShow_Call) Return(err error) *MockAdminScheduleRepository_CreateShow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminScheduleRepository_CreateShow_Call) RunAndReturn(run func(ctx context.Context, show *model.Show) error) *MockAdminScheduleRepository_CreateShow_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteShowByID provides a mock function for the type MockAdminScheduleRepository
func (_mock *MockAdminScheduleRepository) DeleteShowByID(ctx context.Context, showID int) error {
	ret := _mock.Called(ctx, showID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShowByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, showID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminScheduleRepository_DeleteShowByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteShowByID'
type MockAdminScheduleRepository_DeleteShowByID_Call struct {
	*mock.Call
}

// DeleteShowByID is a helper method to define mock.On call
//   - ctx context.Context
//   - showID int
func (_e *MockAdminScheduleRepository_Expecter) DeleteShowByID(ctx interface{}, showID interface{}) *MockAdminScheduleRepository_DeleteShowByID_Call {
	return &MockAdminScheduleRepository_DeleteShowByID_Call{Call: _e.mock.On("DeleteShowByID", ctx, showID)}
}

func (_c *MockAdminScheduleRepository_DeleteShowByID_Call) Run(run func(ctx context.Context, showID int)) *MockAdminScheduleRepository_DeleteShowByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminScheduleRepository_DeleteShowByID_Call) Return(err error) *MockAdminScheduleRepository_DeleteShowByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminScheduleRepository_DeleteShowByID_Call) RunAndReturn(run func(ctx context.Context, showID int) error) *MockAdminScheduleRepository_DeleteShowByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllScreens provides a mock function for the type MockAdminScheduleRepository
func (_mock *MockAdminScheduleRepository) GetAllScreens(ctx context.Context) ([]model.Screen, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllScreens")
	}

	var r0 []model.Screen
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Screen, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Screen); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Screen)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleRepository_GetAllScreens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllScreens'
type MockAdminScheduleRepository_GetAllScreens_Call struct {
	*mock.Call
}

// GetAllScreens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminScheduleRepository_Expecter) GetAllScreens(ctx interface{}) *MockAdminScheduleRepository_GetAllScreens_Call {
	return &MockAdminScheduleRepository_GetAllScreens_Call{Call: _e.mock.On("GetAllScreens", ctx)}
}

func (_c *MockAdminScheduleRepository_GetAllScreens_Call) Run(run func(ctx context.Context)) *MockAdminScheduleRepository_GetAllScreens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminScheduleRepository_GetAllScreens_Call) Return(screens []model.Screen, err error) *MockAdminScheduleRepository_GetAllScreens_Call {
	_c.Call.Return(screens, err)
	return _c
}

func (_c *MockAdminScheduleRepository_GetAllScreens_Call) RunAndReturn(run func(ctx context.Context) ([]model.Screen, error)) *MockAdminScheduleRepository_GetAllScreens_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSlots provides a mock function for the type MockAdminScheduleRepository
func (_mock *MockAdminScheduleRepository) GetAllSlots(ctx context.Context) ([]model.Slot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSlots")
	}

	var r0 []model.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Slot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Slot); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleRepository_GetAllSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSlots'
type MockAdminScheduleRepository_GetAllSlots_Call struct {
	*mock.Call
}

// GetAllSlots is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminScheduleRepository_Expecter) GetAllSlots(ctx interface{}) *MockAdminScheduleRepository_GetAllSlots_Call {
	return &MockAdminScheduleRepository_GetAllSlots_Call{Call: _e.mock.On("GetAllSlots", ctx)}
}

func (_c *MockAdminScheduleRepository_GetAllSlots_Call) Run(run func(ctx context.Context)) *MockAdminScheduleRepository_GetAllSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminScheduleRepository_GetAllSlots_Call) Return(slots []model.Slot, err error) *MockAdminScheduleRepository_GetAllSlots_Call {
	_c.Call.Return(slots, err)
	return _c
}

func (_c *MockAdminScheduleRepository_GetAllSlots_Call) RunAndReturn(run func(ctx context.Context) ([]model.Slot, error)) *MockAdminScheduleRepository_GetAllSlots_Call {
	_c.Call.Return(run)
	return _c
}

// GetShowsInRange provides a mock function for the type MockAdminScheduleRepository
func (_mock *MockAdminScheduleRepository) GetShowsInRange(ctx context.Context, startDate time.Time, endDate time.Time) ([]model.Show, error) {
	ret := _mock.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetShowsInRange")
	}

	var r0 []model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]model.Show, error)); ok {
		return returnFunc(ctx, startDate, endDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []model.Show); ok {
		r0 = returnFunc(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleRepository_GetShowsInRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShowsInRange'
type MockAdminScheduleRepository_GetShowsInRange_Call struct {
	*mock.Call
}

// GetShowsInRange is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockAdminScheduleRepository_Expecter) GetShowsInRange(ctx interface{}, startDate interface{}, endDate interface{}) *MockAdminScheduleRepository_GetShowsInRange_Call {
	return &MockAdminScheduleRepository_GetShowsInRange_Call{Call: _e.mock.On("GetShowsInRange", ctx, startDate, endDate)}
}

func (_c *MockAdminScheduleRepository_GetShowsInRange_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time)) *MockAdminScheduleRepository_GetShowsInRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminScheduleRepository_GetShowsInRange_Call) Return(shows []model.Show, err error) *MockAdminScheduleRepository_GetShowsInRange_Call {
	_c.Call.Return(shows, err)
	return _c
}

func (_c *MockAdminScheduleRepository_GetShowsInRange_Call) RunAndReturn(run func(ctx context.Context, startDate time.Time, endDate time.Time) ([]model.Show, error)) *MockAdminScheduleRepository_GetShowsInRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlotByID provides a mock function for the type MockAdminScheduleRepository
func (_mock *MockAdminScheduleRepository) GetSlotByID(ctx context.Context, slotID int) (*model.Slot, error) {
	ret := _mock.Called(ctx, slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetSlotByID")
	}

	var r0 *model.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*model.Slot, error)); ok {
		return returnFunc(ctx, slotID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *model.Slot); ok {
		r0 = returnFunc(ctx, slotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, slotID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleRepository_GetSlotByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlotByID'
type MockAdminScheduleRepository_GetSlotByID_Call struct {
	*mock.Call
}

// GetSlotByID is a helper method to define mock.On call
//   - ctx context.Context
//   - slotID int
func (_e *MockAdminScheduleRepository_Expecter) GetSlotByID(ctx interface{}, slotID interface{}) *MockAdminScheduleRepository_GetSlotByID_Call {
	return &MockAdminScheduleRepository_GetSlotByID_Call{Call: _e.mock.On("GetSlotByID", ctx, slotID)}
}

func (_c *MockAdminScheduleRepository_GetSlotByID_Call) Run(run func(ctx context.Context, slotID int)) *MockAdminScheduleRepository_GetSlotByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminScheduleRepository_GetSlotByID_Call) Return(slot *model.Slot, err error) *MockAdminScheduleRepository_GetSlotByID_Call {
	_c.Call.Return(slot, err)
	return _c
}

func (_c *MockAdminScheduleRepository_GetSlotByID_Call) RunAndReturn(run func(ctx context.Context, slotID int) (*model.Slot, error)) *MockAdminScheduleRepository_GetSlotByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsSlotOccupied provides a mock function for the type MockAdminScheduleRepository
func (_mock *MockAdminScheduleRepository) IsSlotOccupied(ctx context.Context, screenID int, date time.Time, slotID int) (bool, error) {
	ret := _mock.Called(ctx, screenID, date, slotID)

	if len(ret) == 0 {
		panic("no return value specified for IsSlotOccupied")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, int) (bool, error)); ok {
		return returnFunc(ctx, screenID, date, slotID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time, int) bool); ok {
		r0 = returnFunc(ctx, screenID, date, slotID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time, int) error); ok {
		r1 = returnFunc(ctx, screenID, date, slotID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminScheduleRepository_IsSlotOccupied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSlotOccupied'
type MockAdminScheduleRepository_IsSlotOccupied_Call struct {
	*mock.Call
}

// IsSlotOccupied is a helper method to define mock.On call
//   - ctx context.Context
//   - screenID int
//   - date time.Time
//   - slotID int
func (_e *MockAdminScheduleRepository_Expecter) IsSlotOccupied(ctx interface{}, screenID interface{}, date interface{}, slotID interface{}) *MockAdminScheduleRepository_IsSlotOccupied_Call {
	return &MockAdminScheduleRepository_IsSlotOccupied_Call{Call: _e.mock.On("IsSlotOccupied", ctx, screenID, date, slotID)}
}

func (_c *MockAdminScheduleRepository_IsSlotOccupied_Call) Run(run func(ctx context.Context, screenID int, date time.Time, slotID int)) *MockAdminScheduleRepository_IsSlotOccupied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdminScheduleRepository_IsSlotOccupied_Call) Return(b bool, err error) *MockAdminScheduleRepository_IsSlotOccupied_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAdminScheduleRepository_IsSlotOccupied_Call) RunAndReturn(run func(ctx context.Context, screenID int, date time.Time, slotID int) (bool, error)) *MockAdminScheduleRepository_IsSlotOccupied_Call {
	_c.Call.Return(run)
	return _c
}
