// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingRepository is an autogenerated mock type for the BookingRepository type
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

// BookingAmountByShows provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) BookingAmountByShows(context1 context.Context, ints []int) float64 {
	ret := _mock.Called(context1, ints)

	if len(ret) == 0 {
		panic("no return value specified for BookingAmountByShows")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) float64); ok {
		r0 = returnFunc(context1, ints)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockBookingRepository_BookingAmountByShows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookingAmountByShows'
type MockBookingRepository_BookingAmountByShows_Call struct {
	*mock.Call
}

// BookingAmountByShows is a helper method to define mock.On call
//   - context1 context.Context
//   - ints []int
func (_e *MockBookingRepository_Expecter) BookingAmountByShows(context1 interface{}, ints interface{}) *MockBookingRepository_BookingAmountByShows_Call {
	return &MockBookingRepository_BookingAmountByShows_Call{Call: _e.mock.On("BookingAmountByShows", context1, ints)}
}

func (_c *MockBookingRepository_BookingAmountByShows_Call) Run(run func(context1 context.Context, ints []int)) *MockBookingRepository_BookingAmountByShows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_BookingAmountByShows_Call) Return(f float64) *MockBookingRepository_BookingAmountByShows_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockBookingRepository_BookingAmountByShows_Call) RunAndReturn(run func(context1 context.Context, ints []int) float64) *MockBookingRepository_BookingAmountByShows_Call {
	_c.Call.Return(run)
	return _c
}

// BookingRevenueMap provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) BookingRevenueMap(ctx context.Context, shows []int) map[int]float64 {
	ret := _mock.Called(ctx, shows)

	if len(ret) == 0 {
		panic("no return value specified for BookingRevenueMap")
	}

	var r0 map[int]float64
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) map[int]float64); ok {
		r0 = returnFunc(ctx, shows)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]float64)
		}
	}
	return r0
}

// MockBookingRepository_BookingRevenueMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookingRevenueMap'
type MockBookingRepository_BookingRevenueMap_Call struct {
	*mock.Call
}

// BookingRevenueMap is a helper method to define mock.On call
//   - ctx context.Context
//   - shows []int
func (_e *MockBookingRepository_Expecter) BookingRevenueMap(ctx interface{}, shows interface{}) *MockBookingRepository_BookingRevenueMap_Call {
	return &MockBookingRepository_BookingRevenueMap_Call{Call: _e.mock.On("BookingRevenueMap", ctx, shows)}
}

func (_c *MockBookingRepository_BookingRevenueMap_Call) Run(run func(ctx context.Context, shows []int)) *MockBookingRepository_BookingRevenueMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_BookingRevenueMap_Call) Return(intToFloat64 map[int]float64) *MockBookingRepository_BookingRevenueMap_Call {
	_c.Call.Return(intToFloat64)
	return _c
}

func (_c *MockBookingRepository_BookingRevenueMap_Call) RunAndReturn(run func(ctx context.Context, shows []int) map[int]float64) *MockBookingRepository_BookingRevenueMap_Call {
	_c.Call.Return(run)
	return _c
}
