// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSeatService creates a new instance of MockSeatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeatService {
	mock := &MockSeatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSeatService is an autogenerated mock type for the SeatService type
type MockSeatService struct {
	mock.Mock
}

type MockSeatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeatService) EXPECT() *MockSeatService_Expecter {
	return &MockSeatService_Expecter{mock: &_m.Mock}
}

// GetSeatStatus provides a mock function for the type MockSeatService
func (_mock *MockSeatService) GetSeatStatus(ctx context.Context, showID uint) (*response.SeatStatusResponse, error) {
	ret := _mock.Called(ctx, showID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeatStatus")
	}

	var r0 *response.SeatStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*response.SeatStatusResponse, error)); ok {
		return returnFunc(ctx, showID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *response.SeatStatusResponse); ok {
		r0 = returnFunc(ctx, showID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.SeatStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, showID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatService_GetSeatStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeatStatus'
type MockSeatService_GetSeatStatus_Call struct {
	*mock.Call
}

// GetSeatStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - showID uint
func (_e *MockSeatService_Expecter) GetSeatStatus(ctx interface{}, showID interface{}) *MockSeatService_GetSeatStatus_Call {
	return &MockSeatService_GetSeatStatus_Call{Call: _e.mock.On("GetSeatStatus", ctx, showID)}
}

func (_c *MockSeatService_GetSeatStatus_Call) Run(run func(ctx context.Context, showID uint)) *MockSeatService_GetSeatStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeatService_GetSeatStatus_Call) Return(seatStatusResponse *response.SeatStatusResponse, err error) *MockSeatService_GetSeatStatus_Call {
	_c.Call.Return(seatStatusResponse, err)
	return _c
}

func (_c *MockSeatService_GetSeatStatus_Call) RunAndReturn(run func(ctx context.Context, showID uint) (*response.SeatStatusResponse, error)) *MockSeatService_GetSeatStatus_Call {
	_c.Call.Return(run)
	return _c
}
