// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerBookingService creates a new instance of MockCustomerBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerBookingService {
	mock := &MockCustomerBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerBookingService is an autogenerated mock type for the CustomerBookingService type
type MockCustomerBookingService struct {
	mock.Mock
}

type MockCustomerBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerBookingService) EXPECT() *MockCustomerBookingService_Expecter {
	return &MockCustomerBookingService_Expecter{mock: &_m.Mock}
}

// CheckIn provides a mock function for the type MockCustomerBookingService
func (_mock *MockCustomerBookingService) CheckIn(ctx context.Context, bookingID int) error {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CheckIn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerBookingService_CheckIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIn'
type MockCustomerBookingService_CheckIn_Call struct {
	*mock.Call
}

// CheckIn is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
func (_e *MockCustomerBookingService_Expecter) CheckIn(ctx interface{}, bookingID interface{}) *MockCustomerBookingService_CheckIn_Call {
	return &MockCustomerBookingService_CheckIn_Call{Call: _e.mock.On("CheckIn", ctx, bookingID)}
}

func (_c *MockCustomerBookingService_CheckIn_Call) Run(run func(ctx context.Context, bookingID int)) *MockCustomerBookingService_CheckIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerBookingService_CheckIn_Call) Return(err error) *MockCustomerBookingService_CheckIn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerBookingService_CheckIn_Call) RunAndReturn(run func(ctx context.Context, bookingID int) error) *MockCustomerBookingService_CheckIn_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBooking provides a mock function for the type MockCustomerBookingService
func (_mock *MockCustomerBookingService) CreateBooking(ctx context.Context, customerID int64, showID int, seatStatusIDs []int) (*response.CreateCustomerBookingResponse, error) {
	ret := _mock.Called(ctx, customerID, showID, seatStatusIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *response.CreateCustomerBookingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, []int) (*response.CreateCustomerBookingResponse, error)); ok {
		return returnFunc(ctx, customerID, showID, seatStatusIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, []int) *response.CreateCustomerBookingResponse); ok {
		r0 = returnFunc(ctx, customerID, showID, seatStatusIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CreateCustomerBookingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, []int) error); ok {
		r1 = returnFunc(ctx, customerID, showID, seatStatusIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerBookingService_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockCustomerBookingService_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
//   - showID int
//   - seatStatusIDs []int
func (_e *MockCustomerBookingService_Expecter) CreateBooking(ctx interface{}, customerID interface{}, showID interface{}, seatStatusIDs interface{}) *MockCustomerBookingService_CreateBooking_Call {
	return &MockCustomerBookingService_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, customerID, showID, seatStatusIDs)}
}

func (_c *MockCustomerBookingService_CreateBooking_Call) Run(run func(ctx context.Context, customerID int64, showID int, seatStatusIDs []int)) *MockCustomerBookingService_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []int
		if args[3] != nil {
			arg3 = args[3].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCustomerBookingService_CreateBooking_Call) Return(createCustomerBookingResponse *response.CreateCustomerBookingResponse, err error) *MockCustomerBookingService_CreateBooking_Call {
	_c.Call.Return(createCustomerBookingResponse, err)
	return _c
}

func (_c *MockCustomerBookingService_CreateBooking_Call) RunAndReturn(run func(ctx context.Context, customerID int64, showID int, seatStatusIDs []int) (*response.CreateCustomerBookingResponse, error)) *MockCustomerBookingService_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingDetails provides a mock function for the type MockCustomerBookingService
func (_mock *MockCustomerBookingService) GetBookingDetails(ctx context.Context, bookingID int) (*response.BookingDetailsResponse, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingDetails")
	}

	var r0 *response.BookingDetailsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*response.BookingDetailsResponse, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *response.BookingDetailsResponse); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.BookingDetailsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerBookingService_GetBookingDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingDetails'
type MockCustomerBookingService_GetBookingDetails_Call struct {
	*mock.Call
}

// GetBookingDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
func (_e *MockCustomerBookingService_Expecter) GetBookingDetails(ctx interface{}, bookingID interface{}) *MockCustomerBookingService_GetBookingDetails_Call {
	return &MockCustomerBookingService_GetBookingDetails_Call{Call: _e.mock.On("GetBookingDetails", ctx, bookingID)}
}

func (_c *MockCustomerBookingService_GetBookingDetails_Call) Run(run func(ctx context.Context, bookingID int)) *MockCustomerBookingService_GetBookingDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerBookingService_GetBookingDetails_Call) Return(bookingDetailsResponse *response.BookingDetailsResponse, err error) *MockCustomerBookingService_GetBookingDetails_Call {
	_c.Call.Return(bookingDetailsResponse, err)
	return _c
}

func (_c *MockCustomerBookingService_GetBookingDetails_Call) RunAndReturn(run func(ctx context.Context, bookingID int) (*response.BookingDetailsResponse, error)) *MockCustomerBookingService_GetBookingDetails_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessPayment provides a mock function for the type MockCustomerBookingService
func (_mock *MockCustomerBookingService) ProcessPayment(ctx context.Context, bookingID int, paymentSuccess bool) (*response.PaymentResponse, error) {
	ret := _mock.Called(ctx, bookingID, paymentSuccess)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 *response.PaymentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) (*response.PaymentResponse, error)); ok {
		return returnFunc(ctx, bookingID, paymentSuccess)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) *response.PaymentResponse); ok {
		r0 = returnFunc(ctx, bookingID, paymentSuccess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PaymentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, bookingID, paymentSuccess)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerBookingService_ProcessPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPayment'
type MockCustomerBookingService_ProcessPayment_Call struct {
	*mock.Call
}

// ProcessPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
//   - paymentSuccess bool
func (_e *MockCustomerBookingService_Expecter) ProcessPayment(ctx interface{}, bookingID interface{}, paymentSuccess interface{}) *MockCustomerBookingService_ProcessPayment_Call {
	return &MockCustomerBookingService_ProcessPayment_Call{Call: _e.mock.On("ProcessPayment", ctx, bookingID, paymentSuccess)}
}

func (_c *MockCustomerBookingService_ProcessPayment_Call) Run(run func(ctx context.Context, bookingID int, paymentSuccess bool)) *MockCustomerBookingService_ProcessPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomerBookingService_ProcessPayment_Call) Return(paymentResponse *response.PaymentResponse, err error) *MockCustomerBookingService_ProcessPayment_Call {
	_c.Call.Return(paymentResponse, err)
	return _c
}

func (_c *MockCustomerBookingService_ProcessPayment_Call) RunAndReturn(run func(ctx context.Context, bookingID int, paymentSuccess bool) (*response.PaymentResponse, error)) *MockCustomerBookingService_ProcessPayment_Call {
	_c.Call.Return(run)
	return _c
}
