// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailOTPServiceInterface creates a new instance of MockEmailOTPServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailOTPServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailOTPServiceInterface {
	mock := &MockEmailOTPServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailOTPServiceInterface is an autogenerated mock type for the EmailOTPServiceInterface type
type MockEmailOTPServiceInterface struct {
	mock.Mock
}

type MockEmailOTPServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailOTPServiceInterface) EXPECT() *MockEmailOTPServiceInterface_Expecter {
	return &MockEmailOTPServiceInterface_Expecter{mock: &_m.Mock}
}

// IsRecipientVerified provides a mock function for the type MockEmailOTPServiceInterface
func (_mock *MockEmailOTPServiceInterface) IsRecipientVerified(ctx context.Context, recipient string, otpType string) (bool, error) {
	ret := _mock.Called(ctx, recipient, otpType)

	if len(ret) == 0 {
		panic("no return value specified for IsRecipientVerified")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, recipient, otpType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, recipient, otpType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, recipient, otpType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailOTPServiceInterface_IsRecipientVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRecipientVerified'
type MockEmailOTPServiceInterface_IsRecipientVerified_Call struct {
	*mock.Call
}

// IsRecipientVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - recipient string
//   - otpType string
func (_e *MockEmailOTPServiceInterface_Expecter) IsRecipientVerified(ctx interface{}, recipient interface{}, otpType interface{}) *MockEmailOTPServiceInterface_IsRecipientVerified_Call {
	return &MockEmailOTPServiceInterface_IsRecipientVerified_Call{Call: _e.mock.On("IsRecipientVerified", ctx, recipient, otpType)}
}

func (_c *MockEmailOTPServiceInterface_IsRecipientVerified_Call) Run(run func(ctx context.Context, recipient string, otpType string)) *MockEmailOTPServiceInterface_IsRecipientVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailOTPServiceInterface_IsRecipientVerified_Call) Return(b bool, err error) *MockEmailOTPServiceInterface_IsRecipientVerified_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockEmailOTPServiceInterface_IsRecipientVerified_Call) RunAndReturn(run func(ctx context.Context, recipient string, otpType string) (bool, error)) *MockEmailOTPServiceInterface_IsRecipientVerified_Call {
	_c.Call.Return(run)
	return _c
}

// RequestOTP provides a mock function for the type MockEmailOTPServiceInterface
func (_mock *MockEmailOTPServiceInterface) RequestOTP(ctx context.Context, email string, ip string) (*response.OTPSendResponse, error) {
	ret := _mock.Called(ctx, email, ip)

	if len(ret) == 0 {
		panic("no return value specified for RequestOTP")
	}

	var r0 *response.OTPSendResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*response.OTPSendResponse, error)); ok {
		return returnFunc(ctx, email, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *response.OTPSendResponse); ok {
		r0 = returnFunc(ctx, email, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OTPSendResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailOTPServiceInterface_RequestOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestOTP'
type MockEmailOTPServiceInterface_RequestOTP_Call struct {
	*mock.Call
}

// RequestOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - ip string
func (_e *MockEmailOTPServiceInterface_Expecter) RequestOTP(ctx interface{}, email interface{}, ip interface{}) *MockEmailOTPServiceInterface_RequestOTP_Call {
	return &MockEmailOTPServiceInterface_RequestOTP_Call{Call: _e.mock.On("RequestOTP", ctx, email, ip)}
}

func (_c *MockEmailOTPServiceInterface_RequestOTP_Call) Run(run func(ctx context.Context, email string, ip string)) *MockEmailOTPServiceInterface_RequestOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailOTPServiceInterface_RequestOTP_Call) Return(oTPSendResponse *response.OTPSendResponse, err error) *MockEmailOTPServiceInterface_RequestOTP_Call {
	_c.Call.Return(oTPSendResponse, err)
	return _c
}

func (_c *MockEmailOTPServiceInterface_RequestOTP_Call) RunAndReturn(run func(ctx context.Context, email string, ip string) (*response.OTPSendResponse, error)) *MockEmailOTPServiceInterface_RequestOTP_Call {
	_c.Call.Return(run)
	return _c
}

// ResendOTP provides a mock function for the type MockEmailOTPServiceInterface
func (_mock *MockEmailOTPServiceInterface) ResendOTP(ctx context.Context, email string, ip string) (*response.OTPSendResponse, error) {
	ret := _mock.Called(ctx, email, ip)

	if len(ret) == 0 {
		panic("no return value specified for ResendOTP")
	}

	var r0 *response.OTPSendResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*response.OTPSendResponse, error)); ok {
		return returnFunc(ctx, email, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *response.OTPSendResponse); ok {
		r0 = returnFunc(ctx, email, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OTPSendResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailOTPServiceInterface_ResendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendOTP'
type MockEmailOTPServiceInterface_ResendOTP_Call struct {
	*mock.Call
}

// ResendOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - ip string
func (_e *MockEmailOTPServiceInterface_Expecter) ResendOTP(ctx interface{}, email interface{}, ip interface{}) *MockEmailOTPServiceInterface_ResendOTP_Call {
	return &MockEmailOTPServiceInterface_ResendOTP_Call{Call: _e.mock.On("ResendOTP", ctx, email, ip)}
}

func (_c *MockEmailOTPServiceInterface_ResendOTP_Call) Run(run func(ctx context.Context, email string, ip string)) *MockEmailOTPServiceInterface_ResendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailOTPServiceInterface_ResendOTP_Call) Return(oTPSendResponse *response.OTPSendResponse, err error) *MockEmailOTPServiceInterface_ResendOTP_Call {
	_c.Call.Return(oTPSendResponse, err)
	return _c
}

func (_c *MockEmailOTPServiceInterface_ResendOTP_Call) RunAndReturn(run func(ctx context.Context, email string, ip string) (*response.OTPSendResponse, error)) *MockEmailOTPServiceInterface_ResendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function for the type MockEmailOTPServiceInterface
func (_mock *MockEmailOTPServiceInterface) VerifyOTP(ctx context.Context, email string, code string) (*response.OTPVerifyResponse, error) {
	ret := _mock.Called(ctx, email, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 *response.OTPVerifyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*response.OTPVerifyResponse, error)); ok {
		return returnFunc(ctx, email, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *response.OTPVerifyResponse); ok {
		r0 = returnFunc(ctx, email, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OTPVerifyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailOTPServiceInterface_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockEmailOTPServiceInterface_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
func (_e *MockEmailOTPServiceInterface_Expecter) VerifyOTP(ctx interface{}, email interface{}, code interface{}) *MockEmailOTPServiceInterface_VerifyOTP_Call {
	return &MockEmailOTPServiceInterface_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, email, code)}
}

func (_c *MockEmailOTPServiceInterface_VerifyOTP_Call) Run(run func(ctx context.Context, email string, code string)) *MockEmailOTPServiceInterface_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailOTPServiceInterface_VerifyOTP_Call) Return(oTPVerifyResponse *response.OTPVerifyResponse, err error) *MockEmailOTPServiceInterface_VerifyOTP_Call {
	_c.Call.Return(oTPVerifyResponse, err)
	return _c
}

func (_c *MockEmailOTPServiceInterface_VerifyOTP_Call) RunAndReturn(run func(ctx context.Context, email string, code string) (*response.OTPVerifyResponse, error)) *MockEmailOTPServiceInterface_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}
