// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProfilePictureDeleter creates a new instance of MockProfilePictureDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfilePictureDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfilePictureDeleter {
	mock := &MockProfilePictureDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfilePictureDeleter is an autogenerated mock type for the ProfilePictureDeleter type
type MockProfilePictureDeleter struct {
	mock.Mock
}

type MockProfilePictureDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfilePictureDeleter) EXPECT() *MockProfilePictureDeleter_Expecter {
	return &MockProfilePictureDeleter_Expecter{mock: &_m.Mock}
}

// DeleteByUserID provides a mock function for the type MockProfilePictureDeleter
func (_mock *MockProfilePictureDeleter) DeleteByUserID(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfilePictureDeleter_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockProfilePictureDeleter_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockProfilePictureDeleter_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockProfilePictureDeleter_DeleteByUserID_Call {
	return &MockProfilePictureDeleter_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockProfilePictureDeleter_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockProfilePictureDeleter_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfilePictureDeleter_DeleteByUserID_Call) Return(err error) *MockProfilePictureDeleter_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfilePictureDeleter_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockProfilePictureDeleter_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}
