// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"
	"skyfox/bookings/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShowRepository creates a new instance of MockShowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShowRepository {
	mock := &MockShowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShowRepository is an autogenerated mock type for the ShowRepository type
type MockShowRepository struct {
	mock.Mock
}

type MockShowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShowRepository) EXPECT() *MockShowRepository_Expecter {
	return &MockShowRepository_Expecter{mock: &_m.Mock}
}

// CountAvailableSeats provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) CountAvailableSeats(ctx context.Context, showId int) (int64, error) {
	ret := _mock.Called(ctx, showId)

	if len(ret) == 0 {
		panic("no return value specified for CountAvailableSeats")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return returnFunc(ctx, showId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = returnFunc(ctx, showId)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, showId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_CountAvailableSeats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAvailableSeats'
type MockShowRepository_CountAvailableSeats_Call struct {
	*mock.Call
}

// CountAvailableSeats is a helper method to define mock.On call
//   - ctx context.Context
//   - showId int
func (_e *MockShowRepository_Expecter) CountAvailableSeats(ctx interface{}, showId interface{}) *MockShowRepository_CountAvailableSeats_Call {
	return &MockShowRepository_CountAvailableSeats_Call{Call: _e.mock.On("CountAvailableSeats", ctx, showId)}
}

func (_c *MockShowRepository_CountAvailableSeats_Call) Run(run func(ctx context.Context, showId int)) *MockShowRepository_CountAvailableSeats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowRepository_CountAvailableSeats_Call) Return(n int64, err error) *MockShowRepository_CountAvailableSeats_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockShowRepository_CountAvailableSeats_Call) RunAndReturn(run func(ctx context.Context, showId int) (int64, error)) *MockShowRepository_CountAvailableSeats_Call {
	_c.Call.Return(run)
	return _c
}

// CreateScreen provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) CreateScreen(ctx context.Context, screen *model.Screen) error {
	ret := _mock.Called(ctx, screen)

	if len(ret) == 0 {
		panic("no return value specified for CreateScreen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Screen) error); ok {
		r0 = returnFunc(ctx, screen)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShowRepository_CreateScreen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateScreen'
type MockShowRepository_CreateScreen_Call struct {
	*mock.Call
}

// CreateScreen is a helper method to define mock.On call
//   - ctx context.Context
//   - screen *model.Screen
func (_e *MockShowRepository_Expecter) CreateScreen(ctx interface{}, screen interface{}) *MockShowRepository_CreateScreen_Call {
	return &MockShowRepository_CreateScreen_Call{Call: _e.mock.On("CreateScreen", ctx, screen)}
}

func (_c *MockShowRepository_CreateScreen_Call) Run(run func(ctx context.Context, screen *model.Screen)) *MockShowRepository_CreateScreen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Screen
		if args[1] != nil {
			arg1 = args[1].(*model.Screen)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowRepository_CreateScreen_Call) Return(err error) *MockShowRepository_CreateScreen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShowRepository_CreateScreen_Call) RunAndReturn(run func(ctx context.Context, screen *model.Screen) error) *MockShowRepository_CreateScreen_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) FindById(ctx context.Context, id int) (model.Show, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (model.Show, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) model.Show); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Show)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockShowRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockShowRepository_Expecter) FindById(ctx interface{}, id interface{}) *MockShowRepository_FindById_Call {
	return &MockShowRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockShowRepository_FindById_Call) Run(run func(ctx context.Context, id int)) *MockShowRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowRepository_FindById_Call) Return(show model.Show, err error) *MockShowRepository_FindById_Call {
	_c.Call.Return(show, err)
	return _c
}

func (_c *MockShowRepository_FindById_Call) RunAndReturn(run func(ctx context.Context, id int) (model.Show, error)) *MockShowRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllShowsBy provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) GetAllShowsBy(ctx context.Context, revenueQuery *repository.RevenueQuery) ([]model.Show, error) {
	ret := _mock.Called(ctx, revenueQuery)

	if len(ret) == 0 {
		panic("no return value specified for GetAllShowsBy")
	}

	var r0 []model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.RevenueQuery) ([]model.Show, error)); ok {
		return returnFunc(ctx, revenueQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.RevenueQuery) []model.Show); ok {
		r0 = returnFunc(ctx, revenueQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repository.RevenueQuery) error); ok {
		r1 = returnFunc(ctx, revenueQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_GetAllShowsBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllShowsBy'
type MockShowRepository_GetAllShowsBy_Call struct {
	*mock.Call
}

// GetAllShowsBy is a helper method to define mock.On call
//   - ctx context.Context
//   - revenueQuery *repository.RevenueQuery
func (_e *MockShowRepository_Expecter) GetAllShowsBy(ctx interface{}, revenueQuery interface{}) *MockShowRepository_GetAllShowsBy_Call {
	return &MockShowRepository_GetAllShowsBy_Call{Call: _e.mock.On("GetAllShowsBy", ctx, revenueQuery)}
}

func (_c *MockShowRepository_GetAllShowsBy_Call) Run(run func(ctx context.Context, revenueQuery *repository.RevenueQuery)) *MockShowRepository_GetAllShowsBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.RevenueQuery
		if args[1] != nil {
			arg1 = args[1].(*repository.RevenueQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowRepository_GetAllShowsBy_Call) Return(shows []model.Show, err error) *MockShowRepository_GetAllShowsBy_Call {
	_c.Call.Return(shows, err)
	return _c
}

func (_c *MockShowRepository_GetAllShowsBy_Call) RunAndReturn(run func(ctx context.Context, revenueQuery *repository.RevenueQuery) ([]model.Show, error)) *MockShowRepository_GetAllShowsBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllShowsOn provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) GetAllShowsOn(ctx context.Context, date string) ([]model.Show, error) {
	ret := _mock.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAllShowsOn")
	}

	var r0 []model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Show, error)); ok {
		return returnFunc(ctx, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Show); ok {
		r0 = returnFunc(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_GetAllShowsOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllShowsOn'
type MockShowRepository_GetAllShowsOn_Call struct {
	*mock.Call
}

// GetAllShowsOn is a helper method to define mock.On call
//   - ctx context.Context
//   - date string
func (_e *MockShowRepository_Expecter) GetAllShowsOn(ctx interface{}, date interface{}) *MockShowRepository_GetAllShowsOn_Call {
	return &MockShowRepository_GetAllShowsOn_Call{Call: _e.mock.On("GetAllShowsOn", ctx, date)}
}

func (_c *MockShowRepository_GetAllShowsOn_Call) Run(run func(ctx context.Context, date string)) *MockShowRepository_GetAllShowsOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowRepository_GetAllShowsOn_Call) Return(shows []model.Show, err error) *MockShowRepository_GetAllShowsOn_Call {
	_c.Call.Return(shows, err)
	return _c
}

func (_c *MockShowRepository_GetAllShowsOn_Call) RunAndReturn(run func(ctx context.Context, date string) ([]model.Show, error)) *MockShowRepository_GetAllShowsOn_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableDatesForMovie provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) GetAvailableDatesForMovie(ctx context.Context, movieId string) ([]string, error) {
	ret := _mock.Called(ctx, movieId)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableDatesForMovie")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, movieId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, movieId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, movieId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_GetAvailableDatesForMovie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableDatesForMovie'
type MockShowRepository_GetAvailableDatesForMovie_Call struct {
	*mock.Call
}

// GetAvailableDatesForMovie is a helper method to define mock.On call
//   - ctx context.Context
//   - movieId string
func (_e *MockShowRepository_Expecter) GetAvailableDatesForMovie(ctx interface{}, movieId interface{}) *MockShowRepository_GetAvailableDatesForMovie_Call {
	return &MockShowRepository_GetAvailableDatesForMovie_Call{Call: _e.mock.On("GetAvailableDatesForMovie", ctx, movieId)}
}

func (_c *MockShowRepository_GetAvailableDatesForMovie_Call) Run(run func(ctx context.Context, movieId string)) *MockShowRepository_GetAvailableDatesForMovie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShowRepository_GetAvailableDatesForMovie_Call) Return(strings []string, err error) *MockShowRepository_GetAvailableDatesForMovie_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockShowRepository_GetAvailableDatesForMovie_Call) RunAndReturn(run func(ctx context.Context, movieId string) ([]string, error)) *MockShowRepository_GetAvailableDatesForMovie_Call {
	_c.Call.Return(run)
	return _c
}

// GetScheduledMovieIds provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) GetScheduledMovieIds(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetScheduledMovieIds")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_GetScheduledMovieIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduledMovieIds'
type MockShowRepository_GetScheduledMovieIds_Call struct {
	*mock.Call
}

// GetScheduledMovieIds is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockShowRepository_Expecter) GetScheduledMovieIds(ctx interface{}) *MockShowRepository_GetScheduledMovieIds_Call {
	return &MockShowRepository_GetScheduledMovieIds_Call{Call: _e.mock.On("GetScheduledMovieIds", ctx)}
}

func (_c *MockShowRepository_GetScheduledMovieIds_Call) Run(run func(ctx context.Context)) *MockShowRepository_GetScheduledMovieIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShowRepository_GetScheduledMovieIds_Call) Return(strings []string, err error) *MockShowRepository_GetScheduledMovieIds_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockShowRepository_GetScheduledMovieIds_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockShowRepository_GetScheduledMovieIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetShowsByMovieAndDate provides a mock function for the type MockShowRepository
func (_mock *MockShowRepository) GetShowsByMovieAndDate(ctx context.Context, movieId string, date string) ([]model.Show, error) {
	ret := _mock.Called(ctx, movieId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetShowsByMovieAndDate")
	}

	var r0 []model.Show
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Show, error)); ok {
		return returnFunc(ctx, movieId, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.Show); ok {
		r0 = returnFunc(ctx, movieId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Show)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, movieId, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShowRepository_GetShowsByMovieAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShowsByMovieAndDate'
type MockShowRepository_GetShowsByMovieAndDate_Call struct {
	*mock.Call
}

// GetShowsByMovieAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - movieId string
//   - date string
func (_e *MockShowRepository_Expecter) GetShowsByMovieAndDate(ctx interface{}, movieId interface{}, date interface{}) *MockShowRepository_GetShowsByMovieAndDate_Call {
	return &MockShowRepository_GetShowsByMovieAndDate_Call{Call: _e.mock.On("GetShowsByMovieAndDate", ctx, movieId, date)}
}

func (_c *MockShowRepository_GetShowsByMovieAndDate_Call) Run(run func(ctx context.Context, movieId string, date string)) *MockShowRepository_GetShowsByMovieAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShowRepository_GetShowsByMovieAndDate_Call) Return(shows []model.Show, err error) *MockShowRepository_GetShowsByMovieAndDate_Call {
	_c.Call.Return(shows, err)
	return _c
}

func (_c *MockShowRepository_GetShowsByMovieAndDate_Call) RunAndReturn(run func(ctx context.Context, movieId string, date string) ([]model.Show, error)) *MockShowRepository_GetShowsByMovieAndDate_Call {
	_c.Call.Return(run)
	return _c
}
