// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailOTPRepository creates a new instance of MockEmailOTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailOTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailOTPRepository {
	mock := &MockEmailOTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailOTPRepository is an autogenerated mock type for the EmailOTPRepository type
type MockEmailOTPRepository struct {
	mock.Mock
}

type MockEmailOTPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailOTPRepository) EXPECT() *MockEmailOTPRepository_Expecter {
	return &MockEmailOTPRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEmailOTPRepository
func (_mock *MockEmailOTPRepository) Create(ctx context.Context, otp *model.OTPVerification) error {
	ret := _mock.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.OTPVerification) error); ok {
		r0 = returnFunc(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailOTPRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEmailOTPRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - otp *model.OTPVerification
func (_e *MockEmailOTPRepository_Expecter) Create(ctx interface{}, otp interface{}) *MockEmailOTPRepository_Create_Call {
	return &MockEmailOTPRepository_Create_Call{Call: _e.mock.On("Create", ctx, otp)}
}

func (_c *MockEmailOTPRepository_Create_Call) Run(run func(ctx context.Context, otp *model.OTPVerification)) *MockEmailOTPRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.OTPVerification
		if args[1] != nil {
			arg1 = args[1].(*model.OTPVerification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailOTPRepository_Create_Call) Return(err error) *MockEmailOTPRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailOTPRepository_Create_Call) RunAndReturn(run func(ctx context.Context, otp *model.OTPVerification) error) *MockEmailOTPRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByRecipient provides a mock function for the type MockEmailOTPRepository
func (_mock *MockEmailOTPRepository) FindActiveByRecipient(ctx context.Context, recipient string, otpType string) (*model.OTPVerification, error) {
	ret := _mock.Called(ctx, recipient, otpType)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByRecipient")
	}

	var r0 *model.OTPVerification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.OTPVerification, error)); ok {
		return returnFunc(ctx, recipient, otpType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.OTPVerification); ok {
		r0 = returnFunc(ctx, recipient, otpType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OTPVerification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, recipient, otpType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailOTPRepository_FindActiveByRecipient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByRecipient'
type MockEmailOTPRepository_FindActiveByRecipient_Call struct {
	*mock.Call
}

// FindActiveByRecipient is a helper method to define mock.On call
//   - ctx context.Context
//   - recipient string
//   - otpType string
func (_e *MockEmailOTPRepository_Expecter) FindActiveByRecipient(ctx interface{}, recipient interface{}, otpType interface{}) *MockEmailOTPRepository_FindActiveByRecipient_Call {
	return &MockEmailOTPRepository_FindActiveByRecipient_Call{Call: _e.mock.On("FindActiveByRecipient", ctx, recipient, otpType)}
}

func (_c *MockEmailOTPRepository_FindActiveByRecipient_Call) Run(run func(ctx context.Context, recipient string, otpType string)) *MockEmailOTPRepository_FindActiveByRecipient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailOTPRepository_FindActiveByRecipient_Call) Return(oTPVerification *model.OTPVerification, err error) *MockEmailOTPRepository_FindActiveByRecipient_Call {
	_c.Call.Return(oTPVerification, err)
	return _c
}

func (_c *MockEmailOTPRepository_FindActiveByRecipient_Call) RunAndReturn(run func(ctx context.Context, recipient string, otpType string) (*model.OTPVerification, error)) *MockEmailOTPRepository_FindActiveByRecipient_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockEmailOTPRepository
func (_mock *MockEmailOTPRepository) FindAll(ctx context.Context) ([]model.OTPVerification, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.OTPVerification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.OTPVerification, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.OTPVerification); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OTPVerification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailOTPRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockEmailOTPRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEmailOTPRepository_Expecter) FindAll(ctx interface{}) *MockEmailOTPRepository_FindAll_Call {
	return &MockEmailOTPRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockEmailOTPRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockEmailOTPRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmailOTPRepository_FindAll_Call) Return(oTPVerifications []model.OTPVerification, err error) *MockEmailOTPRepository_FindAll_Call {
	_c.Call.Return(oTPVerifications, err)
	return _c
}

func (_c *MockEmailOTPRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.OTPVerification, error)) *MockEmailOTPRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementAttempts provides a mock function for the type MockEmailOTPRepository
func (_mock *MockEmailOTPRepository) IncrementAttempts(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAttempts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailOTPRepository_IncrementAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementAttempts'
type MockEmailOTPRepository_IncrementAttempts_Call struct {
	*mock.Call
}

// IncrementAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockEmailOTPRepository_Expecter) IncrementAttempts(ctx interface{}, id interface{}) *MockEmailOTPRepository_IncrementAttempts_Call {
	return &MockEmailOTPRepository_IncrementAttempts_Call{Call: _e.mock.On("IncrementAttempts", ctx, id)}
}

func (_c *MockEmailOTPRepository_IncrementAttempts_Call) Run(run func(ctx context.Context, id int)) *MockEmailOTPRepository_IncrementAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailOTPRepository_IncrementAttempts_Call) Return(err error) *MockEmailOTPRepository_IncrementAttempts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailOTPRepository_IncrementAttempts_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockEmailOTPRepository_IncrementAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidatePreviousOTPs provides a mock function for the type MockEmailOTPRepository
func (_mock *MockEmailOTPRepository) InvalidatePreviousOTPs(ctx context.Context, recipient string, otpType string) error {
	ret := _mock.Called(ctx, recipient, otpType)

	if len(ret) == 0 {
		panic("no return value specified for InvalidatePreviousOTPs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, recipient, otpType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailOTPRepository_InvalidatePreviousOTPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidatePreviousOTPs'
type MockEmailOTPRepository_InvalidatePreviousOTPs_Call struct {
	*mock.Call
}

// InvalidatePreviousOTPs is a helper method to define mock.On call
//   - ctx context.Context
//   - recipient string
//   - otpType string
func (_e *MockEmailOTPRepository_Expecter) InvalidatePreviousOTPs(ctx interface{}, recipient interface{}, otpType interface{}) *MockEmailOTPRepository_InvalidatePreviousOTPs_Call {
	return &MockEmailOTPRepository_InvalidatePreviousOTPs_Call{Call: _e.mock.On("InvalidatePreviousOTPs", ctx, recipient, otpType)}
}

func (_c *MockEmailOTPRepository_InvalidatePreviousOTPs_Call) Run(run func(ctx context.Context, recipient string, otpType string)) *MockEmailOTPRepository_InvalidatePreviousOTPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailOTPRepository_InvalidatePreviousOTPs_Call) Return(err error) *MockEmailOTPRepository_InvalidatePreviousOTPs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailOTPRepository_InvalidatePreviousOTPs_Call) RunAndReturn(run func(ctx context.Context, recipient string, otpType string) error) *MockEmailOTPRepository_InvalidatePreviousOTPs_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function for the type MockEmailOTPRepository
func (_mock *MockEmailOTPRepository) MarkUsed(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailOTPRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockEmailOTPRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockEmailOTPRepository_Expecter) MarkUsed(ctx interface{}, id interface{}) *MockEmailOTPRepository_MarkUsed_Call {
	return &MockEmailOTPRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id)}
}

func (_c *MockEmailOTPRepository_MarkUsed_Call) Run(run func(ctx context.Context, id int)) *MockEmailOTPRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailOTPRepository_MarkUsed_Call) Return(err error) *MockEmailOTPRepository_MarkUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailOTPRepository_MarkUsed_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockEmailOTPRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}
