// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOwnerAdminRepository creates a new instance of MockOwnerAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOwnerAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOwnerAdminRepository {
	mock := &MockOwnerAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOwnerAdminRepository is an autogenerated mock type for the OwnerAdminRepository type
type MockOwnerAdminRepository struct {
	mock.Mock
}

type MockOwnerAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOwnerAdminRepository) EXPECT() *MockOwnerAdminRepository_Expecter {
	return &MockOwnerAdminRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOwnerAdminRepository
func (_mock *MockOwnerAdminRepository) Create(context1 context.Context, customer *model.Customer) error {
	ret := _mock.Called(context1, customer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Customer) error); ok {
		r0 = returnFunc(context1, customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOwnerAdminRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOwnerAdminRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - customer *model.Customer
func (_e *MockOwnerAdminRepository_Expecter) Create(context1 interface{}, customer interface{}) *MockOwnerAdminRepository_Create_Call {
	return &MockOwnerAdminRepository_Create_Call{Call: _e.mock.On("Create", context1, customer)}
}

func (_c *MockOwnerAdminRepository_Create_Call) Run(run func(context1 context.Context, customer *model.Customer)) *MockOwnerAdminRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Customer
		if args[1] != nil {
			arg1 = args[1].(*model.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnerAdminRepository_Create_Call) Return(err error) *MockOwnerAdminRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOwnerAdminRepository_Create_Call) RunAndReturn(run func(context1 context.Context, customer *model.Customer) error) *MockOwnerAdminRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockOwnerAdminRepository
func (_mock *MockOwnerAdminRepository) DeleteByID(context1 context.Context, v uint) error {
	ret := _mock.Called(context1, v)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(context1, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOwnerAdminRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockOwnerAdminRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint
func (_e *MockOwnerAdminRepository_Expecter) DeleteByID(context1 interface{}, v interface{}) *MockOwnerAdminRepository_DeleteByID_Call {
	return &MockOwnerAdminRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", context1, v)}
}

func (_c *MockOwnerAdminRepository_DeleteByID_Call) Run(run func(context1 context.Context, v uint)) *MockOwnerAdminRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnerAdminRepository_DeleteByID_Call) Return(err error) *MockOwnerAdminRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOwnerAdminRepository_DeleteByID_Call) RunAndReturn(run func(context1 context.Context, v uint) error) *MockOwnerAdminRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByRole provides a mock function for the type MockOwnerAdminRepository
func (_mock *MockOwnerAdminRepository) FindAllByRole(context1 context.Context, s string) ([]model.Customer, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByRole")
	}

	var r0 []model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Customer, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Customer); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerAdminRepository_FindAllByRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByRole'
type MockOwnerAdminRepository_FindAllByRole_Call struct {
	*mock.Call
}

// FindAllByRole is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockOwnerAdminRepository_Expecter) FindAllByRole(context1 interface{}, s interface{}) *MockOwnerAdminRepository_FindAllByRole_Call {
	return &MockOwnerAdminRepository_FindAllByRole_Call{Call: _e.mock.On("FindAllByRole", context1, s)}
}

func (_c *MockOwnerAdminRepository_FindAllByRole_Call) Run(run func(context1 context.Context, s string)) *MockOwnerAdminRepository_FindAllByRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnerAdminRepository_FindAllByRole_Call) Return(customers []model.Customer, err error) *MockOwnerAdminRepository_FindAllByRole_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *MockOwnerAdminRepository_FindAllByRole_Call) RunAndReturn(run func(context1 context.Context, s string) ([]model.Customer, error)) *MockOwnerAdminRepository_FindAllByRole_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockOwnerAdminRepository
func (_mock *MockOwnerAdminRepository) FindByEmail(context1 context.Context, s string) (*model.Customer, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Customer, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerAdminRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockOwnerAdminRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockOwnerAdminRepository_Expecter) FindByEmail(context1 interface{}, s interface{}) *MockOwnerAdminRepository_FindByEmail_Call {
	return &MockOwnerAdminRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", context1, s)}
}

func (_c *MockOwnerAdminRepository_FindByEmail_Call) Run(run func(context1 context.Context, s string)) *MockOwnerAdminRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnerAdminRepository_FindByEmail_Call) Return(customer *model.Customer, err error) *MockOwnerAdminRepository_FindByEmail_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockOwnerAdminRepository_FindByEmail_Call) RunAndReturn(run func(context1 context.Context, s string) (*model.Customer, error)) *MockOwnerAdminRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockOwnerAdminRepository
func (_mock *MockOwnerAdminRepository) FindByID(context1 context.Context, v uint) (*model.Customer, error) {
	ret := _mock.Called(context1, v)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*model.Customer, error)); ok {
		return returnFunc(context1, v)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *model.Customer); ok {
		r0 = returnFunc(context1, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(context1, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerAdminRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOwnerAdminRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint
func (_e *MockOwnerAdminRepository_Expecter) FindByID(context1 interface{}, v interface{}) *MockOwnerAdminRepository_FindByID_Call {
	return &MockOwnerAdminRepository_FindByID_Call{Call: _e.mock.On("FindByID", context1, v)}
}

func (_c *MockOwnerAdminRepository_FindByID_Call) Run(run func(context1 context.Context, v uint)) *MockOwnerAdminRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnerAdminRepository_FindByID_Call) Return(customer *model.Customer, err error) *MockOwnerAdminRepository_FindByID_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockOwnerAdminRepository_FindByID_Call) RunAndReturn(run func(context1 context.Context, v uint) (*model.Customer, error)) *MockOwnerAdminRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockOwnerAdminRepository
func (_mock *MockOwnerAdminRepository) FindByUsername(context1 context.Context, s string) (*model.Customer, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Customer, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnerAdminRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockOwnerAdminRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockOwnerAdminRepository_Expecter) FindByUsername(context1 interface{}, s interface{}) *MockOwnerAdminRepository_FindByUsername_Call {
	return &MockOwnerAdminRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", context1, s)}
}

func (_c *MockOwnerAdminRepository_FindByUsername_Call) Run(run func(context1 context.Context, s string)) *MockOwnerAdminRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnerAdminRepository_FindByUsername_Call) Return(customer *model.Customer, err error) *MockOwnerAdminRepository_FindByUsername_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockOwnerAdminRepository_FindByUsername_Call) RunAndReturn(run func(context1 context.Context, s string) (*model.Customer, error)) *MockOwnerAdminRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}
