// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/dto/request"
	"skyfox/bookings/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingViewRepository creates a new instance of MockBookingViewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingViewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingViewRepository {
	mock := &MockBookingViewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingViewRepository is an autogenerated mock type for the BookingViewRepository type
type MockBookingViewRepository struct {
	mock.Mock
}

type MockBookingViewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingViewRepository) EXPECT() *MockBookingViewRepository_Expecter {
	return &MockBookingViewRepository_Expecter{mock: &_m.Mock}
}

// GetAllBookings provides a mock function for the type MockBookingViewRepository
func (_mock *MockBookingViewRepository) GetAllBookings(ctx context.Context, filter request.AdminBookingViewRequest) ([]repository.BookingViewRow, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBookings")
	}

	var r0 []repository.BookingViewRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.AdminBookingViewRequest) ([]repository.BookingViewRow, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.AdminBookingViewRequest) []repository.BookingViewRow); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.BookingViewRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.AdminBookingViewRequest) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingViewRepository_GetAllBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBookings'
type MockBookingViewRepository_GetAllBookings_Call struct {
	*mock.Call
}

// GetAllBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - filter request.AdminBookingViewRequest
func (_e *MockBookingViewRepository_Expecter) GetAllBookings(ctx interface{}, filter interface{}) *MockBookingViewRepository_GetAllBookings_Call {
	return &MockBookingViewRepository_GetAllBookings_Call{Call: _e.mock.On("GetAllBookings", ctx, filter)}
}

func (_c *MockBookingViewRepository_GetAllBookings_Call) Run(run func(ctx context.Context, filter request.AdminBookingViewRequest)) *MockBookingViewRepository_GetAllBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.AdminBookingViewRequest
		if args[1] != nil {
			arg1 = args[1].(request.AdminBookingViewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingViewRepository_GetAllBookings_Call) Return(bookingViewRows []repository.BookingViewRow, err error) *MockBookingViewRepository_GetAllBookings_Call {
	_c.Call.Return(bookingViewRows, err)
	return _c
}

func (_c *MockBookingViewRepository_GetAllBookings_Call) RunAndReturn(run func(ctx context.Context, filter request.AdminBookingViewRequest) ([]repository.BookingViewRow, error)) *MockBookingViewRepository_GetAllBookings_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBookingsCustomer provides a mock function for the type MockBookingViewRepository
func (_mock *MockBookingViewRepository) GetAllBookingsCustomer(ctx context.Context, filter request.CustomerBookingViewRequest) ([]repository.BookingViewRow, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBookingsCustomer")
	}

	var r0 []repository.BookingViewRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CustomerBookingViewRequest) ([]repository.BookingViewRow, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.CustomerBookingViewRequest) []repository.BookingViewRow); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.BookingViewRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.CustomerBookingViewRequest) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingViewRepository_GetAllBookingsCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBookingsCustomer'
type MockBookingViewRepository_GetAllBookingsCustomer_Call struct {
	*mock.Call
}

// GetAllBookingsCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - filter request.CustomerBookingViewRequest
func (_e *MockBookingViewRepository_Expecter) GetAllBookingsCustomer(ctx interface{}, filter interface{}) *MockBookingViewRepository_GetAllBookingsCustomer_Call {
	return &MockBookingViewRepository_GetAllBookingsCustomer_Call{Call: _e.mock.On("GetAllBookingsCustomer", ctx, filter)}
}

func (_c *MockBookingViewRepository_GetAllBookingsCustomer_Call) Run(run func(ctx context.Context, filter request.CustomerBookingViewRequest)) *MockBookingViewRepository_GetAllBookingsCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.CustomerBookingViewRequest
		if args[1] != nil {
			arg1 = args[1].(request.CustomerBookingViewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingViewRepository_GetAllBookingsCustomer_Call) Return(bookingViewRows []repository.BookingViewRow, err error) *MockBookingViewRepository_GetAllBookingsCustomer_Call {
	_c.Call.Return(bookingViewRows, err)
	return _c
}

func (_c *MockBookingViewRepository_GetAllBookingsCustomer_Call) RunAndReturn(run func(ctx context.Context, filter request.CustomerBookingViewRequest) ([]repository.BookingViewRow, error)) *MockBookingViewRepository_GetAllBookingsCustomer_Call {
	_c.Call.Return(run)
	return _c
}
