// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"skyfox/bookings/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAvatarRepository creates a new instance of MockAvatarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarRepository {
	mock := &MockAvatarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAvatarRepository is an autogenerated mock type for the AvatarRepository type
type MockAvatarRepository struct {
	mock.Mock
}

type MockAvatarRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarRepository) EXPECT() *MockAvatarRepository_Expecter {
	return &MockAvatarRepository_Expecter{mock: &_m.Mock}
}

// BulkInsertIfNotExists provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) BulkInsertIfNotExists(ctx context.Context, avatars []model.PredefinedAvatar) error {
	ret := _mock.Called(ctx, avatars)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsertIfNotExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.PredefinedAvatar) error); ok {
		r0 = returnFunc(ctx, avatars)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarRepository_BulkInsertIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsertIfNotExists'
type MockAvatarRepository_BulkInsertIfNotExists_Call struct {
	*mock.Call
}

// BulkInsertIfNotExists is a helper method to define mock.On call
//   - ctx context.Context
//   - avatars []model.PredefinedAvatar
func (_e *MockAvatarRepository_Expecter) BulkInsertIfNotExists(ctx interface{}, avatars interface{}) *MockAvatarRepository_BulkInsertIfNotExists_Call {
	return &MockAvatarRepository_BulkInsertIfNotExists_Call{Call: _e.mock.On("BulkInsertIfNotExists", ctx, avatars)}
}

func (_c *MockAvatarRepository_BulkInsertIfNotExists_Call) Run(run func(ctx context.Context, avatars []model.PredefinedAvatar)) *MockAvatarRepository_BulkInsertIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.PredefinedAvatar
		if args[1] != nil {
			arg1 = args[1].([]model.PredefinedAvatar)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_BulkInsertIfNotExists_Call) Return(err error) *MockAvatarRepository_BulkInsertIfNotExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarRepository_BulkInsertIfNotExists_Call) RunAndReturn(run func(ctx context.Context, avatars []model.PredefinedAvatar) error) *MockAvatarRepository_BulkInsertIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByURL provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) ExistsByURL(ctx context.Context, url string) (bool, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByURL")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_ExistsByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByURL'
type MockAvatarRepository_ExistsByURL_Call struct {
	*mock.Call
}

// ExistsByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockAvatarRepository_Expecter) ExistsByURL(ctx interface{}, url interface{}) *MockAvatarRepository_ExistsByURL_Call {
	return &MockAvatarRepository_ExistsByURL_Call{Call: _e.mock.On("ExistsByURL", ctx, url)}
}

func (_c *MockAvatarRepository_ExistsByURL_Call) Run(run func(ctx context.Context, url string)) *MockAvatarRepository_ExistsByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_ExistsByURL_Call) Return(b bool, err error) *MockAvatarRepository_ExistsByURL_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAvatarRepository_ExistsByURL_Call) RunAndReturn(run func(ctx context.Context, url string) (bool, error)) *MockAvatarRepository_ExistsByURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) GetByID(ctx context.Context, id int64) (*model.PredefinedAvatar, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.PredefinedAvatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.PredefinedAvatar, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.PredefinedAvatar); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PredefinedAvatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAvatarRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAvatarRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAvatarRepository_GetByID_Call {
	return &MockAvatarRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAvatarRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockAvatarRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_GetByID_Call) Return(predefinedAvatar *model.PredefinedAvatar, err error) *MockAvatarRepository_GetByID_Call {
	_c.Call.Return(predefinedAvatar, err)
	return _c
}

func (_c *MockAvatarRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*model.PredefinedAvatar, error)) *MockAvatarRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomByGender provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) GetRandomByGender(ctx context.Context, gender string) (*model.PredefinedAvatar, error) {
	ret := _mock.Called(ctx, gender)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomByGender")
	}

	var r0 *model.PredefinedAvatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.PredefinedAvatar, error)); ok {
		return returnFunc(ctx, gender)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.PredefinedAvatar); ok {
		r0 = returnFunc(ctx, gender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PredefinedAvatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, gender)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_GetRandomByGender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomByGender'
type MockAvatarRepository_GetRandomByGender_Call struct {
	*mock.Call
}

// GetRandomByGender is a helper method to define mock.On call
//   - ctx context.Context
//   - gender string
func (_e *MockAvatarRepository_Expecter) GetRandomByGender(ctx interface{}, gender interface{}) *MockAvatarRepository_GetRandomByGender_Call {
	return &MockAvatarRepository_GetRandomByGender_Call{Call: _e.mock.On("GetRandomByGender", ctx, gender)}
}

func (_c *MockAvatarRepository_GetRandomByGender_Call) Run(run func(ctx context.Context, gender string)) *MockAvatarRepository_GetRandomByGender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_GetRandomByGender_Call) Return(predefinedAvatar *model.PredefinedAvatar, err error) *MockAvatarRepository_GetRandomByGender_Call {
	_c.Call.Return(predefinedAvatar, err)
	return _c
}

func (_c *MockAvatarRepository_GetRandomByGender_Call) RunAndReturn(run func(ctx context.Context, gender string) (*model.PredefinedAvatar, error)) *MockAvatarRepository_GetRandomByGender_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAvatar provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) GetUserAvatar(ctx context.Context, userID uint) (string, string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAvatar")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (string, string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) string); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAvatarRepository_GetUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAvatar'
type MockAvatarRepository_GetUserAvatar_Call struct {
	*mock.Call
}

// GetUserAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockAvatarRepository_Expecter) GetUserAvatar(ctx interface{}, userID interface{}) *MockAvatarRepository_GetUserAvatar_Call {
	return &MockAvatarRepository_GetUserAvatar_Call{Call: _e.mock.On("GetUserAvatar", ctx, userID)}
}

func (_c *MockAvatarRepository_GetUserAvatar_Call) Run(run func(ctx context.Context, userID uint)) *MockAvatarRepository_GetUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_GetUserAvatar_Call) Return(avatarURL string, avatarType string, err error) *MockAvatarRepository_GetUserAvatar_Call {
	_c.Call.Return(avatarURL, avatarType, err)
	return _c
}

func (_c *MockAvatarRepository_GetUserAvatar_Call) RunAndReturn(run func(ctx context.Context, userID uint) (string, string, error)) *MockAvatarRepository_GetUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) ListAll(ctx context.Context) ([]model.PredefinedAvatar, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []model.PredefinedAvatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.PredefinedAvatar, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.PredefinedAvatar); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PredefinedAvatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockAvatarRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAvatarRepository_Expecter) ListAll(ctx interface{}) *MockAvatarRepository_ListAll_Call {
	return &MockAvatarRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockAvatarRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockAvatarRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_ListAll_Call) Return(predefinedAvatars []model.PredefinedAvatar, err error) *MockAvatarRepository_ListAll_Call {
	_c.Call.Return(predefinedAvatars, err)
	return _c
}

func (_c *MockAvatarRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.PredefinedAvatar, error)) *MockAvatarRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListByGender provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) ListByGender(ctx context.Context, gender string) ([]model.PredefinedAvatar, error) {
	ret := _mock.Called(ctx, gender)

	if len(ret) == 0 {
		panic("no return value specified for ListByGender")
	}

	var r0 []model.PredefinedAvatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.PredefinedAvatar, error)); ok {
		return returnFunc(ctx, gender)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.PredefinedAvatar); ok {
		r0 = returnFunc(ctx, gender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PredefinedAvatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, gender)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_ListByGender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByGender'
type MockAvatarRepository_ListByGender_Call struct {
	*mock.Call
}

// ListByGender is a helper method to define mock.On call
//   - ctx context.Context
//   - gender string
func (_e *MockAvatarRepository_Expecter) ListByGender(ctx interface{}, gender interface{}) *MockAvatarRepository_ListByGender_Call {
	return &MockAvatarRepository_ListByGender_Call{Call: _e.mock.On("ListByGender", ctx, gender)}
}

func (_c *MockAvatarRepository_ListByGender_Call) Run(run func(ctx context.Context, gender string)) *MockAvatarRepository_ListByGender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_ListByGender_Call) Return(predefinedAvatars []model.PredefinedAvatar, err error) *MockAvatarRepository_ListByGender_Call {
	_c.Call.Return(predefinedAvatars, err)
	return _c
}

func (_c *MockAvatarRepository_ListByGender_Call) RunAndReturn(run func(ctx context.Context, gender string) ([]model.PredefinedAvatar, error)) *MockAvatarRepository_ListByGender_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserAvatar provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) UpdateUserAvatar(ctx context.Context, userID uint, avatarURL string, avatarType string) error {
	ret := _mock.Called(ctx, userID, avatarURL, avatarType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = returnFunc(ctx, userID, avatarURL, avatarType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarRepository_UpdateUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserAvatar'
type MockAvatarRepository_UpdateUserAvatar_Call struct {
	*mock.Call
}

// UpdateUserAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - avatarURL string
//   - avatarType string
func (_e *MockAvatarRepository_Expecter) UpdateUserAvatar(ctx interface{}, userID interface{}, avatarURL interface{}, avatarType interface{}) *MockAvatarRepository_UpdateUserAvatar_Call {
	return &MockAvatarRepository_UpdateUserAvatar_Call{Call: _e.mock.On("UpdateUserAvatar", ctx, userID, avatarURL, avatarType)}
}

func (_c *MockAvatarRepository_UpdateUserAvatar_Call) Run(run func(ctx context.Context, userID uint, avatarURL string, avatarType string)) *MockAvatarRepository_UpdateUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_UpdateUserAvatar_Call) Return(err error) *MockAvatarRepository_UpdateUserAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarRepository_UpdateUserAvatar_Call) RunAndReturn(run func(ctx context.Context, userID uint, avatarURL string, avatarType string) error) *MockAvatarRepository_UpdateUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}
