// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCaptchaServiceInterface creates a new instance of MockCaptchaServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCaptchaServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCaptchaServiceInterface {
	mock := &MockCaptchaServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCaptchaServiceInterface is an autogenerated mock type for the CaptchaServiceInterface type
type MockCaptchaServiceInterface struct {
	mock.Mock
}

type MockCaptchaServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCaptchaServiceInterface) EXPECT() *MockCaptchaServiceInterface_Expecter {
	return &MockCaptchaServiceInterface_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockCaptchaServiceInterface
func (_mock *MockCaptchaServiceInterface) Generate() (string, string, string, int, int, int, int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 int
	var r4 int
	var r5 int
	var r6 int
	var r7 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, string, int, int, int, int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() string); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func() int); ok {
		r3 = returnFunc()
	} else {
		r3 = ret.Get(3).(int)
	}
	if returnFunc, ok := ret.Get(4).(func() int); ok {
		r4 = returnFunc()
	} else {
		r4 = ret.Get(4).(int)
	}
	if returnFunc, ok := ret.Get(5).(func() int); ok {
		r5 = returnFunc()
	} else {
		r5 = ret.Get(5).(int)
	}
	if returnFunc, ok := ret.Get(6).(func() int); ok {
		r6 = returnFunc()
	} else {
		r6 = ret.Get(6).(int)
	}
	if returnFunc, ok := ret.Get(7).(func() error); ok {
		r7 = returnFunc()
	} else {
		r7 = ret.Error(7)
	}
	return r0, r1, r2, r3, r4, r5, r6, r7
}

// MockCaptchaServiceInterface_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockCaptchaServiceInterface_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockCaptchaServiceInterface_Expecter) Generate() *MockCaptchaServiceInterface_Generate_Call {
	return &MockCaptchaServiceInterface_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockCaptchaServiceInterface_Generate_Call) Run(run func()) *MockCaptchaServiceInterface_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCaptchaServiceInterface_Generate_Call) Return(captchaID string, masterImage string, tileImage string, tileX int, tileY int, tileWidth int, tileHeight int, err error) *MockCaptchaServiceInterface_Generate_Call {
	_c.Call.Return(captchaID, masterImage, tileImage, tileX, tileY, tileWidth, tileHeight, err)
	return _c
}

func (_c *MockCaptchaServiceInterface_Generate_Call) RunAndReturn(run func() (string, string, string, int, int, int, int, error)) *MockCaptchaServiceInterface_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockCaptchaServiceInterface
func (_mock *MockCaptchaServiceInterface) Verify(captchaID string, sliderPositionX float64) bool {
	ret := _mock.Called(captchaID, sliderPositionX)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, float64) bool); ok {
		r0 = returnFunc(captchaID, sliderPositionX)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCaptchaServiceInterface_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockCaptchaServiceInterface_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - captchaID string
//   - sliderPositionX float64
func (_e *MockCaptchaServiceInterface_Expecter) Verify(captchaID interface{}, sliderPositionX interface{}) *MockCaptchaServiceInterface_Verify_Call {
	return &MockCaptchaServiceInterface_Verify_Call{Call: _e.mock.On("Verify", captchaID, sliderPositionX)}
}

func (_c *MockCaptchaServiceInterface_Verify_Call) Run(run func(captchaID string, sliderPositionX float64)) *MockCaptchaServiceInterface_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCaptchaServiceInterface_Verify_Call) Return(b bool) *MockCaptchaServiceInterface_Verify_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCaptchaServiceInterface_Verify_Call) RunAndReturn(run func(captchaID string, sliderPositionX float64) bool) *MockCaptchaServiceInterface_Verify_Call {
	_c.Call.Return(run)
	return _c
}
